### DISCUSSION TITLE
Changing the logo

### DISCUSSION THREAD

**Discussion by sudadabdul** [open-metadata/OpenMetadata#10525] [Q&A]
Hi there,

I've been trying to change the logo by following the "How to add a custom logo for the application" docs, but I get error that states that applicationConfig is not valid. How can I fix it or How can I change the logo?

Thank you very much.

**Comment by luis-fnogueira** [comment]
Same error here

**Reply by luis-fnogueira** [reply]
@Sachin-chaurasiya in my case, in the docker-compose.yml, under the environment of the server container I added this:
```
     [...]
      OPENMETADATA_HEAP_OPTS: ${OPENMETADATA_HEAP_OPTS:--Xmx1G -Xms1G}
      #Custom images
      applicationConfig:
        logoConfig:
          customLogoUrlPath: "https://i.postimg.cc/66zsh7QD/17-03-Logo-clicksign-time-de-dados-sem-margem-150-60px.png"
          customMonogramUrlPath: "https://i.postimg.cc/SQVszxbK/17-03-Logo-clicksign-time-de-dados-sem-margem-30px.png"
```

**Reply by Sachin-chaurasiya** [reply]
> @Sachin-chaurasiya in my case, in the docker-compose.yml, under the environment of the server container I added this:
> 
> ```
> 
>      [...]
> 
>       OPENMETADATA_HEAP_OPTS: ${OPENMETADATA_HEAP_OPTS:--Xmx1G -Xms1G}
> 
>       #Custom images
> 
>       applicationConfig:
> 
>         logoConfig:
> 
>           customLogoUrlPath: "https://i.postimg.cc/66zsh7QD/17-03-Logo-clicksign-time-de-dados-sem-margem-150-60px.png"
> 
>           customMonogramUrlPath: "https://i.postimg.cc/SQVszxbK/17-03-Logo-clicksign-time-de-dados-sem-margem-30px.png"
> 
> ```

You will have to add the environment value like this 

https://github.com/open-metadata/OpenMetadata/blob/e4c0c7245bc8d42f14dfc764f38a8020ba89c536/docker/local-metadata/docker-compose-postgres.yml#L113

**Comment by Sachin-chaurasiya** [comment]
> Hi there,
> 
> I've been trying to change the logo by following the "How to add a custom logo for the application" docs, but I get error that states that applicationConfig is not valid. How can I fix it or How can I change the logo?
> 
> Thank you very much.

@sudadabdul Can you share the error logs?


The application config should be like this, can you verify the same?

```yml

applicationConfig:
  logoConfig:
    customLogoUrlPath: ${OM_CUSTOM_LOGO_URL_PATH:-""} #login page logo
    customMonogramUrlPath: ${OM_CUSTOM_MONOGRAM_URL_PATH:-""} #nav bar logo
  loginConfig:
    maxLoginFailAttempts: ${OM_MAX_FAILED_LOGIN_ATTEMPTS:-3}
    accessBlockTime: ${OM_LOGIN_ACCESS_BLOCK_TIME:-600}
    jwtTokenExpiryTime: ${OM_JWT_EXPIRY_TIME:-3600}

```
