### DISCUSSION TITLE
Error:: Superset Ingestion based on Snowflake tables - lineage Error -

### DISCUSSION THREAD

**Discussion by mazenorabi** [open-metadata/OpenMetadata#16867] [General]
When Running superset ingestion job externally, Dashboard and Tables lineage is not appearing due to the below Error:

`WARNING  {metadata.Ingestion:status:76} - Error to yield dashboard lineage details for DB service name [service_SNOWFLAKE_DB]: 'Engine' object has no attribute 'fetch_datasource'`

**service_SNOWFLAKE_DB**: is the snowflake database service name which has been ingested into OpenMetaData already.

The Yaml file looks like this:
```
source:
  type: superset
  serviceName: local_superset
  serviceConnection:
    config:
      type: Superset      
      hostPort: {{ SUPERSET_HOST }}
      connection:
        type: Postgres
        username: {{ USER }}
        authType:
          password: {{ PASSWORD }}
        hostPort: {{ POSTGRESQL_DB }}:5432
        database: superset
  sourceConfig:
    config:
      type: DashboardMetadata
      lineageInformation:
        dbServiceNames:
          - service_SNOWFLAKE_DB
      includeTags: true
      includeDataModels: true
      includeOwners: false
      markDeletedDashboards: true    
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: <HOST>/api
    authProvider: openmetadata
    verifySSL: ignore
    securityConfig:
      jwtToken: "***"
    storeServiceConnection: true
```
dashboards and charts seems like ingested but not the lineage, any advices?

OpenMetaData Version: **1.4.2**
