### DISCUSSION TITLE
Opensearch as Search Engine Deployment with AWS IAM Authentication

### DISCUSSION THREAD

**Discussion by jz-xie** [open-metadata/OpenMetadata#20217] [Q&A] [answered]
Ask shown in [the document here ](https://docs.open-metadata.org/latest/deployment/kubernetes/eks#aws-services-for-database-as-rds-and-search-engine-as-elasticsearch)

Seems like only user and password is supported for Opensearch. It would be useful to have AWS IAM authentication supported as well.

**Comment by Prajwal214** [comment]
Ref - https://docs.open-metadata.org/latest/deployment/rds-iam-auth

**Reply by jz-xie** [reply]
Hi @Prajwal214 

Does the IAM auth also works for OpenSearch?

**Comment by FFCMSouza** [comment]
My AWS Opensearch only have IAM and Cognito authentication. I was unable to connect with opensearch using either method.
Is there a way to authenticate Opensearch using any of these approachs?

**Reply by jzzzzzzzzz-z** [reply]
There is tool might be useful for you:

https://github.com/awslabs/aws-sigv4-proxy

You can try deploy this tool as a sidecar container of OpenMetadata to sign its OpenSearch requests, with you AWS IAM role attached in service account. 

I have not deployed it myself because the latest version has a critical vulnerability that would not pass my security check.

**Comment by jzzzzzzzzz-z** [comment, marked as answer]
Sharing a working solution in EKS deployment:

Attach the application service account with a AWS IAM role that has access your AWS OpenSearch instance, config your helm values like the following

```
openmetadata:
  config:
    elasticsearch:
      enabled: true
      host: localhost
      searchType: opensearch
      port: 8080
      scheme: http
      connectionTimeoutSecs: 5
      socketTimeoutSecs: 60
      keepAliveTimeoutSecs: 600
      batchSize: 10
      auth:
        enabled: false


sidecars:
- name: "aws-sigv4-proxy"
  image: "<aws-sigv4-proxy-image> https://github.com/awslabs/aws-sigv4-proxy"
  imagePullPolicy: "Always"
  command: ["./aws-sigv4-proxy"]
  args: 
  - "--verbose"
  - "--log-failed-requests"
  - "--log-signing-process"
  - "--no-verify-ssl"
  - "--name"
  - "es"
  - "--region"
  - "<Your AWS Region>"
  - "--host"
  - "<Your AWS Opensearch Host>"
  - "--sign-host"
  - "<Your AWS Opensearch Host>"
  env:
  - name: AWS_SDK_LOAD_CONFIG
    value: "true"
```
