### ISSUE TITLE
WebAnalyticEntity Report throws error when entity was deleted

### ISSUE THREAD

**Issue by parthasarathy93** [open-metadata/OpenMetadata#10173]
I am using the version 0.13.0 and used the same version of OM Ingestion Package for doing this. I was trying to remove the dependency on airflow and do the ingestions using sdks, so trying to do the DataInsightWorkflow in a similar way . This is the code

#
```
import pathlib
import yaml
import os
from metadata.config.common import load_config_file
from metadata.data_insight.api.workflow import DataInsightWorkflow
from metadata.ingestion.api.workflow import Workflow

def metadata_ingestion_workflow(config):
    workflow_config = yaml.safe_load(config)
    workflow = DataInsightWorkflow.create(workflow_config)
    workflow.execute()
    workflow.raise_from_status()
    workflow.print_status()
    workflow.stop()
def main():
    with open("/Users/pganesan/PycharmProjects/omconnector/datainsghts.yml") as file:
        # use safe_load instead load
        config = file.read()
        print(config)
        metadata_ingestion_workflow(config)

if __name__ == "__main__":
    main()
    
```
    
    
    
    
    
 Yaml file:
        
```
 source:
    type: dataInsight
    serviceName: openMetadata
    serviceConnection: null
    sourceConfig:
      config:
        type: MetadataToElasticSearch
  processor:
    type: data-insight-processor
    config: {}
  sink:
    type: elasticsearch
    config:
      scheme: http
      es_host: sg-metis-6003
      es_port: '9200'
  stage: null
  workflowConfig:
    openMetadataServerConfig:
      hostPort: http://sg-metis-6003:8585/api
      authProvider: openmetadata
      securityConfig:
        jwtToken: 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmdlc3Rpb24tYm90IiwiaXNCb3QiOnRydWUsImlzcyI6Im9wZW4tbWV0YWRhdGEub3JnIiwiaWF0IjoxNjY5ODY5NzYyLCJlbWFpbCI6ImluZ2VzdGlvbi1ib3RAb3Blbm1ldGFkYXRhLm9yZyJ9.g5JUJ-GVqHlUWEMuFkb9YbzdwGnV8MdDgPlUAxg6V2eUsIw5T3y9mfmYWHpIWyMBIsM-BKS4S80mwie1xIndk7cJv7esVeJxt-iiRtmuDoqoj4UoLQ4GO_mB_DwK_whiS8Lj9McwrUlMJV2ylER420onPhwIOuhWU3lxyroQKRqHDjJ0485V1TyAl-r14nK0ksIVyR3SGDWaYoF6URRuaWvik19s7Z-6mMyFWW0QwQa8qF1Gw4K9CNIjzoXH4YjiNEZNIGh4m2WehcG1KBByxygXKnrf9veLlrmCHgJSle6EZR7934XPkyEXGT-JP8I4fTOaqvfJrxShrP1KfjvIRg'
    
```
