### ISSUE TITLE
Fail ingesting query usage

### ISSUE THREAD

**Issue by joseongil-zb** [open-metadata/OpenMetadata#10215]
**Affected module**
BE

**Describe the bug**
I’m using OMD v.0.13.2 ,
At v0.13.1  I succeeded ingesting Athena query usage with metadata ingest -c <path.yaml>  command,
but at v0.13.2 it fails with error message below with same csv and yaml.
Also there are ‘schema_name’ field and values in csv file

```
[2023-02-15 06:01:15] INFO     {metadata.Ingestion:workflow:116} - Service type:ServiceType.Database,query-log-usage configured
[2023-02-15 06:01:16] INFO     {metadata.Utils:logger:165} -
Error initializing USAGE: 'QueryLogUsageSource' object has no attribute 'schema_field'
```

**To Reproduce**
metadata ingest -c <path.yaml>  

**Expected behavior**
ingest successfully

**Version:**
 - OpenMetadata version: 0.13.2

**Additional context**
I asked about this issue at slack
https://openmetadata.slack.com/archives/C02B6955S4S/p1676441146216039

**Comment by RedHotUnicorn** [comment]
I also have this error @ulixius9 

```
Error initializing USAGE: 'QueryLogUsageSource' object has no attribute 'schema_field'
```

I have the next csv 
```
query_text,database_name,schema_name
"create table dbo.t1 as select * from dbo.t2 join dbo.t3 on t2.id = t3.dsb_id ",default,dbo
```

and the next yaml
```
source: 
  type: query-log-usage
  serviceName: default
  sourceConfig: 
    config: 
      type: DatabaseUsage
      queryLogFilePath: "/tmp/queries.csv"
processor: 
  type: query-parser
  config: {}
stage: 
  type: table-usage
  config: 
    filename: "/tmp/query-usage"
bulkSink: 
  type: metadata-usage
  config: 
    filename: "/tmp/query-usage"
workflowConfig: 
  openMetadataServerConfig: 
    hostPort: "http://127.0.0.1:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: "~~~"
```
