### ISSUE TITLE
Custom Login Logo does not change after adding new custom logo

### ISSUE THREAD

**Issue by CheyenneRobinson** [open-metadata/OpenMetadata#11503]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
It affects the UI.

**Describe the bug**
I have followed the directions located on the url provided on changing the custom log but after completing the changes the Login logo does not change to the new custom logo. The application was also stop and started again.  The navigation logo changed successfully although it flickers back to the default log if you click it.  It then changes back to the new custom logo.

https://docs.open-metadata.org/v1.0.0/how-to-guides/how-to-add-custom-logo

**To Reproduce**
Follow the instructions from the above URL and then test whether is was applied.  Stop and the start OpenMetadata.

Screenshots or steps to reproduce
<img width="282" alt="Screenshot 2023-05-09 072919" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/4f1e2498-05ad-4d44-81fc-ffd279ceebf8">
<img width="408" alt="Screenshot 2023-05-09 072731" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/cd1fc54c-9ed1-4d70-96e8-b490c5985168">
<img width="1340" alt="Screenshot 2023-05-09 072305" src="https://github.com/open-metadata/OpenMetadata/assets/131470710/45913b74-a983-4ab7-b2ae-cef201ba4875">

**Expected behavior**
I expected the Login log to change to the new custom logo as the directions states.

**Version:**
 - OS: RHEL 8.6
 - Python version: 3.9.13
 - OpenMetadata version: 1.0
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.0.0.0

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
Hello @CheyenneRobinson , Thanks for filing an issue, however, it's not reproducible on our end.

Here is the config I tried with and it worked as expected.

```
applicationConfig:
  logoConfig:
    customLogoUrlPath: ${OM_CUSTOM_LOGO_URL_PATH:-"https://user-images.githubusercontent.com/59080942/155874645-939f754a-35ee-4fed-a68a-465f55981a7f.png"} #login page logo
    customMonogramUrlPath: ${OM_CUSTOM_MONOGRAM_URL_PATH:-"https://user-images.githubusercontent.com/59080942/155874645-939f754a-35ee-4fed-a68a-465f55981a7f.png"} #nav bar logo
```


https://github.com/open-metadata/OpenMetadata/assets/59080942/8feb0b3e-b828-48c4-beae-90967f02d614


Can you check if you get the proper `logoConfig` from this endpoint `api/v1/system/config/applicationConfig` response?
Also, may I know, if both images are hosted on the same domain?
