### ISSUE TITLE
Can't create custom storage connector for non-S3 sources

### ISSUE THREAD

**Issue by joshliberty** [open-metadata/OpenMetadata#12528]
**Affected module**
SDK

**Describe the bug**
The json schemas only allow the S3 storage service connection object to be used in the ServiceConnection definition. This prevents the framework from running any custom (non-s3) storage connector.

**To Reproduce**
1. Create any workflow config with a source definition as follows:
```
source:
  type: customStorage
  serviceName: custom_NAME
  serviceConnection:
    config:
      type: CustomStorage
      sourcePythonClass: SOURCE_CLASS
      connectionOptions:
        CUSTOM_PARAMS
```
2. Try to run the workflow
3. A validation error occurs, since the serviceConnection values aren't compatible with the S3 service connection definition.

**Expected behavior**
1. The workflow passes validation and the source is executed

**Version:**
 - OS: Windows/Any
 - Python version: 3.10.11
 - OpenMetadata version: N/A
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.1.0.3
