### ISSUE TITLE
Different path URL

### ISSUE THREAD

**Issue by ricgatti** [open-metadata/OpenMetadata#13155]
**Is some content missing, wrong or not clear?**
I'm trying to use ingress object to access to opemetadata web page but can't fine any example

**Describe the solution you'd like**
Try to write some example of values.yaml for installation

**Additional context**
I have setup the inrgess section like this
```
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: HOSTNAME
      paths:
        - path: /openmeta
          pathType: ImplementationSpecific
  tls:
    - secretName: cert-secret
      hosts:
        - HOSTNAME

``` 
the tls section and creation of the ingress object seemd right but when i try to open https://HOSTNAME/openmeta i get this error
![image](https://github.com/open-metadata/OpenMetadata/assets/3082496/17f1d9c7-4a29-477d-a04b-fd5b04127432)
