### ISSUE TITLE
Ingress URL path

### ISSUE THREAD

**Issue by ricgatti** [open-metadata/OpenMetadata#13156]
I'm trying to use ingress object to access to opemetadata web page but can't fine any example of values.yaml file to use. I can't use the / as path because we run different application in the same cluster.

**Additional context**
I have setup the inrgess section like this
```
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: HOSTNAME
      paths:
        - path: /openmeta
          pathType: ImplementationSpecific
  tls:
    - secretName: cert-secret
      hosts:
        - HOSTNAME

``` 
the tls section and creation of the ingress object seemd right but when i try to open https://HOSTNAME/openmeta i get this error
![image](https://github.com/open-metadata/OpenMetadata/assets/3082496/17f1d9c7-4a29-477d-a04b-fd5b04127432)
