### ISSUE TITLE
DBT tag glossaries

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#13293]
**Is your feature request related to a problem? Please describe.**
Currently, the DBT importer can only import arbitrary tags. However, it would be great if it can at least link to already pre-created glossary entries

**Describe the solution you'd like**
- similar to the tags allow to link to a pre-existing glossary entry
- ideally, allow to create glossary entries

**Comment by geoHeil** [comment]
yes something like this.

ideally with an extension where descriptions in DBT format which are referenced from Markdown files with an ID could auto-generate these glossaries (if maybe placed in a special folder of the DBT project).

**Comment by tdeenes** [comment]
I think the best option is to use the [meta](https://docs.getdbt.com/reference/resource-configs/meta) field with an `openmetadata` key in the dbt yaml file. This would allow for linking an already existing glossary term or define a new one, e.g.:
```
    tables:
      - name: DATA_TABLE
        description: Data ,
        columns:
          - name: gross_revenue
            description: column description
            meta:
              openmetadata:
                - type: GlossaryTerm
                  fullyQualifiedName: BusinessGlossary.GrossRevenue
```
