### ISSUE TITLE
Failed to parse the query (DBT ingestion)

### ISSUE THREAD

**Issue by mriveraFacephi** [open-metadata/OpenMetadata#13713]
**Affected module**
Ingestion Framework

**Describe the bug**
I'm using OpenMetadata 1.0.5 for ingesting dbt (meta)data with openmetadata-ingestion tool. I'm using DBT 1.6.x.
When ingesting dbt files in OpenMetadata, the following messages appears continuously:

`WARNING  {metadata.Ingestion:metadata:678} - Failed to parse the query`

The process appears to end correctly:

```
[2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Total processed records: 324
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Total warnings: 0
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Total filtered: 0
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Total errors: 0
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Success %: 100.0
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Workflow finished in time: 27.0m 2.8s
[2023-10-26, 05:39:43 UTC] {pod_manager.py:381} INFO - [2023-10-26 05:39:29] INFO     {metadata.Utils:logger:183} - Workflow finished successfully
```

Furthermore, I'm continuously receiving this message:

`WARNING  {metadata.OMetaAPI:patch_mixin:82} - The entity with id [athena-metadata-ingestion.awsdatacatalog.bd_stg_db_medallion.silver_view.record_family] already has a description. To overwrite it, set force to True.`

I don't find where put `force` to True.

**To Reproduce**

- `yaml` file:

```
source:
  type: dbt
  serviceName: ${SERVICE_NAME}
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
         dbtCatalogFilePath: ${EFS_DBT_METADATA}/target/catalog.json
         dbtManifestFilePath: ${EFS_DBT_METADATA}/target/manifest.json
         dbtRunResultsFilePath: ${EFS_DBT_METADATA}/target/run_results.json
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: ${HOST_PORT}
    authProvider: openmetadata
    forceEntityOverwriting: True
    securityConfig:
      ...
```

**Expected behavior**
Ingesting dbt metadata without warnings.

**Version:**
 - OS: Docker image (python:3.8)
 - Python version: 3.8
 - OpenMetadata version: 1.0.5
 - OpenMetadata Ingestion package version: openmetadata-ingestion==1.0.5.0
 - dbt-artifacts-parser (required package): dbt-artifacts-parser==0.4.2
 - dbt-core version: 1.6.5

**Additional context**

The size of the log generated by OpenMetadata Ingestion in this process is bigger than 5MiB (!) due to the amount of warning messages that are raised.

Any help is appreciated. Thank you.
