### ISSUE TITLE
Add support of JSON logs

### ISSUE THREAD

**Issue by Sudokamikaze** [open-metadata/OpenMetadata#14318]
**Is your feature request related to a problem? Please describe.**
We would like to have logs messages formatted as a JSON to inject them later on into ELK stack helping users to see the OMD logs in a proper place

**Describe the solution you'd like**
Something like:
```
  appenders:
    - type: file
      layout:
        type: json
```
Would be awesome, as right now it's not possible to have logs formatted as JSON out of logback

**Describe alternatives you've considered**
None

**Additional context**
None
