### ISSUE TITLE
docker-compose failed randomly without healthcheck of elasticsearch.  

### ISSUE THREAD

**Issue by kenyyh** [open-metadata/OpenMetadata#14854]
**Is your feature request related to a problem? Please describe.**

Current docker-compose.yaml only do health check on Backend Database Mysql / Postgres.
https://github.com/open-metadata/OpenMetadata/blob/main/docker/docker-compose-quickstart/docker-compose-postgres.yml

However, sometime it takes a long time to start elasticsearch in a small test environment.
When we try to start the environment using docker it will failed randomly since the container **execute-migrate-all** may timeout when trying to access elasticsearch.  

**Describe alternatives you've considered**
I think the health check on elasticsearch should be add in order to make sure that the setup process can be stable.  

Current yaml
```
execute-migrate-all:
    container_name: execute_migrate_all
    image: docker.getcollate.io/openmetadata/server:1.2.4
    command: "./bootstrap/bootstrap_storage.sh migrate-all"
    environment:
      ...skip
    depends_on:
      elasticsearch:
        condition: service_started
      postgresql:
        condition: service_healthy
    networks:
      - app_net

  openmetadata-server:
    depends_on:
      elasticsearch:
        condition: service_started
      postgresql:
        condition: service_healthy
      execute-migrate-all:
        condition: service_completed_successfully
```

Expected yaml
```
  elasticsearch:
    ...skip
    healthcheck:
      test: curl http://localhost:9200
      interval: 15s
      timeout: 10s
      retries: 10

execute-migrate-all:
    container_name: execute_migrate_all
    image: docker.getcollate.io/openmetadata/server:1.2.4
    command: "./bootstrap/bootstrap_storage.sh migrate-all"
    environment:
      ...skip
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    networks:
      - app_net

  openmetadata-server:
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      execute-migrate-all:
        condition: service_completed_successfully
```

**Additional context**
