### ISSUE TITLE
The Quickstart Local Docker Deployment manual does not work on Mac.

### ISSUE THREAD

**Issue by gyuni99** [open-metadata/OpenMetadata#15177]
**Describe the bug**
The code below is the MySQL section from the docker-compose.yml.
docker-compose.yml
```yaml
version: "3.9"
volumes:
  ingestion-volume-dag-airflow:
  ingestion-volume-dags:
  ingestion-volume-tmp:
  es-data:
services:
  mysql:
    container_name: openmetadata_mysql
    image: docker.getcollate.io/openmetadata/db:1.3.0
    command: "--sort_buffer_size=10M"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
     - ./docker-volume/db-data:/var/lib/mysql
    networks:
      - app_net
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --silent --execute "use openmetadata_db"
      interval: 15s
      timeout: 10s
      retries: 10
```

Running docker compose up results in the following error.
command : docker compose -f docker-compose.yml up
```shell
09:30:00 abc@abc-mac openmetadata → docker compose -f docker-compose.yml up
[+] Running 5/5
 ✔ Container openmetadata_mysql          Recreated                                                                                                                                                                                                                                                                                                         0.5s
 ✔ Container openmetadata_elasticsearch  Running                                                                                                                                                                                                                                                                                                           0.0s
 ✔ Container execute_migrate_all         Recreated                                                                                                                                                                                                                                                                                                         0.4s
 ✔ Container openmetadata_server         Recreated                                                                                                                                                                                                                                                                                                         0.4s
 ✔ Container openmetadata_ingestion      Recreated                                                                                                                                                                                                                                                                                                         0.4s
Attaching to execute_migrate_all, openmetadata_elasticsearch, openmetadata_ingestion, openmetadata_mysql, openmetadata_server
openmetadata_mysql          | [Entrypoint] MySQL Docker Image 8.0.32-1.2.11-server
openmetadata_mysql          | [Entrypoint] Initializing database
openmetadata_mysql          | 2024-02-14T00:30:04.175320Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
openmetadata_mysql          | 2024-02-14T00:30:04.175372Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.32) initializing of server in progress as process 17
openmetadata_mysql          | 2024-02-14T00:30:04.185325Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
openmetadata_mysql          | 2024-02-14T00:30:04.187209Z 0 [ERROR] [MY-010174] [Server] Can't change data directory owner to mysql
openmetadata_mysql          | 2024-02-14T00:30:04.187213Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
openmetadata_mysql          | 2024-02-14T00:30:04.187249Z 0 [ERROR] [MY-010119] [Server] Aborting
openmetadata_mysql          | 2024-02-14T00:30:04.187333Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
openmetadata_mysql exited with code 0
dependency failed to start: container openmetadata_mysql is unhealthy
```
Adding the Mac's user/group to the docker-compose file still results in the same issue.

**Version:**
 - OS: Mac Sonoma 14.3
 - OpenMetadata version: 1.3.0
 - Docker: Docker version 25.0.3, build 4debf411d1
 - Docker Compose: Docker Compose version 2.24.5

**Additional context**
Use Docker and Docker Compose CLI for installation without using Docker Desktop.
The docker-compose.yml was downloaded from the following link: https://github.com/open-metadata/OpenMetadata/releases/download/1.3.0-release/docker-compose.yml
