### ISSUE TITLE
Using CustomDashboard source type leads to wrong import of get_connection function

### ISSUE THREAD

**Issue by aballiet** [open-metadata/OpenMetadata#15446]
**Affected module**

- ingestion

**Describe the bug**

When using a `CustomDashboard` config type, OpenMetadata will look for the `get_connection` internally instead of where the custom pythonClass is located

**To Reproduce**

```YAML
type: customDash
serviceName: periscope_connector
serviceConnection:
  config:
    type: CustomDashboard
    sourcePythonClass: <MY_LOCAL_PATH>
```

Screenshots or steps to reproduce

`DynamicImportException: Cannot load object from metadata.ingestion.source.dashboard.customdashboard.connection.get_connection due to No module named 'metadata.ingestion.source.dashboard.customdashboard'`

<img width="1018" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/25565600/196bce15-58ff-41c0-98e2-0af5b865a539">

**Expected behavior**

Expected behavior is to look inside same pythonClass as defined in YAML config with param `sourcePythonClass`

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
