### ISSUE TITLE
My user can create services without admin permissions

### ISSUE THREAD

**Issue by rubenssoto** [open-metadata/OpenMetadata#1578]
Hello everyone,

<img width="1792" alt="Captura de Tela 2021-12-06 às 13 09 12" src="https://user-images.githubusercontent.com/36298331/144889770-cebdfb8e-4f00-4bf4-a47a-c0cf7c5c02c4.png">
<img width="1390" alt="Captura de Tela 2021-12-06 às 13 05 32" src="https://user-images.githubusercontent.com/36298331/144889781-14a9dbc8-9ebe-4b86-a867-e9dc5d1a4707.png">

My user don't have admin rules but I can create services.

**Comment by rubenssoto** [comment]
Only to add more things:

I don't see any restriction to my user, I can create tags, edit them, create teams etc...

My user was admin before, I don't if it could causing the issue.

**Comment by harshach** [comment]
@rubenssoto can you confirm if you set a google SSO to access the openMetadata. In non-secure mode where we don't have any login, we allow all users to make changes across the site. 
Example here 
https://github.com/open-metadata/OpenMetadata/blob/main/conf/openmetadata-security.yaml#L116
if you didn't pass that config, It will configured to a NoOpAuthorizer which doesn't check and returns true all the time.

**Comment by rubenssoto** [comment]
My config is:

```
authorizerConfiguration:
  className: "org.openmetadata.catalog.security.DefaultCatalogAuthorizer"
  # JWT Filter
  containerRequestFilter: "org.openmetadata.catalog.security.JwtFilter"
  adminPrincipals:
    - "rodrigo"
  botPrincipals:
    - "ingestion-bot"
  principalDomain: "DOMAIN"
```

When I tried to login with my personal gmail account:
<img width="1701" alt="Captura de Tela 2021-12-06 às 19 38 53" src="https://user-images.githubusercontent.com/36298331/144934182-070f5a4e-f1b7-4de7-b084-48e1c8ab6c65.png">
