### ISSUE TITLE
Error when creating test cases if the table contains the name COLUMN

### ISSUE THREAD

**Issue by triquinielas** [open-metadata/OpenMetadata#15856]
**DATA QUALITY TEST CASE**

**Describe the bug**
If the name of the table contains the word COLUMN it fails when creating a test case, it has been tested with different tables that contain the word and all of them fail, but if they do not contain the word COLUMN it works correctly.

**To Reproduce**
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/a14a36d1-e627-4417-baf5-f1196ac8b509)

**Expected behavior**
The performance is expected to be the same because a table can contain the name column, we have +180 tables with this nomenclature.

**Version:**
 - OpenMetadata version: 1.3.2

**Additional context**
we assume it will happen with more reserved words, but we have detected COLUMN

**Comment by sushi30** [comment]
requires https://github.com/open-metadata/OpenMetadata/issues/9686

**Comment by TeddyCr** [comment]
@triquinielas I am not able to reproduce your error. Would you have the server logs to share by any chance

![Screenshot 2024-04-26 at 4 42 12 PM](https://github.com/open-metadata/OpenMetadata/assets/13626425/51d77232-8265-4964-9aa1-ce817853b4d4)

**Comment by triquinielas** [comment]
Hi @TeddyCr , thanks for your feedback, I will try to do some more testing and let you know, see if I am able to find any patterns.

**Comment by triquinielas** [comment]
hI @TeddyCr ,

I keep getting the same error, I have tried the latest version 1.3.3.

I have created in **snowflake** the following tables to try to make quality test, I have tried different combinations of uppercase, lowercase, and the term columns,column and col included.

CREATE OR REPLACE TABLE DIM_DATA_QUALITY_COLUMN AS SELECT 1 AS ID;
CREATE OR REPLACE TABLE foo_column AS SELECT 1 AS ID;
CREATE OR REPLACE TABLE foo_columns AS SELECT 1 AS ID;
CREATE OR REPLACE TABLE foo_column AS SELECT 1 AS ID; CREATE OR REPLACE TABLE foo_column AS SELECT 1 AS ID
CREATE OR REPLACE TABLE DIM_DATA_COLUMNS AS SELECT 1 AS ID;

CREATE OR REPLACE TABLE foo_col AS SELECT 1 AS ID; CREATE OR REPLACE TABLE foo_col AS SELECT 1 AS ID
CREATE OR REPLACE TABLE DIM_DATA_QUALITY_COL AS SELECT 1 AS ID;

Only let me do quality test in foo_col and DIM_DATA_QUALITY_COL (last two), the rest gives me errors.

If I create a "table" test, I can do test case in all but if I do add test column, it fails me if it has the word COLUMN or COLUMNS.
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/0bbb3086-0888-49c6-8088-137e54a8b75d)


Look at the error that gives open_metadata: table instance for HBX_SNOWFLAKE.HBG_GOVERNANCE.COMMUNITY_ANALYTICS.**DIM_DATA_**ID**S** not found
![image](https://github.com/open-metadata/OpenMetadata/assets/139678112/7a7ba2c7-9763-4bbf-8fc3-e132b3d0944a)

It's as if the word COLUMN disappears from the composition, when it should be HBX_SNOWFLAKE.HBG_GOVERNANCE.COMMUNITY_ANALYTICS.DIM_**DATA_**COLUMN**S**

thanks,
Carlos

**Comment by TeddyCr** [comment]
Thanks @triquinielas let me try to replicate it in Snowflake

**Comment by TeddyCr** [comment]
I was able to reproduce it. Thanks @triquinielas for the details. 

![Image](https://github.com/open-metadata/OpenMetadata/assets/13626425/80d6f2bb-c0bb-48b0-a052-9aff3619f4bb)

**Comment by triquinielas** [comment]
Hi @TeddyCr, thanks for your effort and for trying identify the issue.

**Comment by TeddyCr** [comment]
@triquinielas in the meantime you should be able to create/run your test cases for this table via the CLI tool. More info [here](https://docs.open-metadata.org/v1.3.x/connectors/ingestion/workflows/data-quality)

```
source:
  type: TestSuite
  serviceName: MySQL
  sourceConfig:
    config:
      type: TestSuite
      entityFullyQualifiedName: MySQL.default.openmetadata_db.DIM_DATA_COLUMN

processor:
  type: "orm-test-runner"
  config:
    testCases:
      - name: myTestName
        description: test description
        columnName: ID
        testDefinitionName: columnValuesToBeUnique
        computePassedFailedRowCount: true

sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: <token>
```
