### ISSUE TITLE
Add custom Meta from dbt into the Custom Properties tab

### ISSUE THREAD

**Issue by AboutManuel** [open-metadata/OpenMetadata#16050]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**

- Ingesting tables that come from dbt

We would like to add the meta that comes from the `schema.yml` file, in this example, to create a property called `model_dag` and automatically fetch it from the artifact `manifest.json`.

```
version: 2

models:
  - name: <model_name>
    description: "<model_description>"
    meta:
      model_dag: "<user_input>"
```

**Describe alternatives you've considered**
Another catalog that is also open source has this already implemented this if you want to explore a similar feature.

**Additional context**

![image](https://github.com/open-metadata/OpenMetadata/assets/16685401/2afe3c75-6288-4ca9-b006-0ade33ab6155)
