### ISSUE TITLE
dbt docs column name is case sensitive on ingest

### ISSUE THREAD

**Issue by zerfix** [open-metadata/OpenMetadata#16091]
**Affected module**
dbt ingestion

**Describe the bug**
Column descriptions from dbt docs are only applied when column name case matches exactly with what has already been pulled from snowflake. The nature of SQL means that the column name case in snowflake might not match what is defined dbt models (when not escaped) or dbt docs.

**To Reproduce**
1. Create dbt prodject
2. Add seed `seed/test_seed.csv`
```csv
smal,smalbig,BIG
1,2,3
```
3. Add dbt documentation for seed `seed/schema.yml`
```yml
version: 2
seeds:
  - name: test_seed
    columns:
      - name: smal # These names are case sensitive in context of OpenMetadata ingest
        description: Small source and doc name.
      - name: SMALBIG
        description: Small source and big doc name.
      - name: BIG
        description: Big source and doc name.
```
4. Run `dbt seed`
5. Run `dbt docs generate`
6. Ingest database
7. Ingest dbt
8. You should now see column description from dbt in OpenMetadata for column `SMALBIG` and `BIG` but not `SMAL`.

**Expected behavior**
Import dbt column descriptions independent of column name case, unless it would cause name collision.

**Version:**
 - OS: Fedora
 - Python version: 3.11
 - OpenMetadata version: 1.3.3 (docker image)
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[snowflake]=1.3.3.0`
