### ISSUE TITLE
[Ingestion] Error while using the SAP HANA Connector with SQL Connection

### ISSUE THREAD

**Issue by MirrerZu** [open-metadata/OpenMetadata#16249]
**Affected module**
Ingestion Framework

**Describe the bug**
When I attempt to connect SapHana using SQL Connection in demo docker, it throws a error like
`{"error": "Error running automation workflow due to [Cannot load object from metadata.ingestion.source.database.saphana.connection.get_connection due to cannot import name 'HdbUserStoreConnection' from 'metadata.generated.schema.entity.services.connections.database.sapHanaConnection' (/home/airflow/.local/lib/python3.10/site-packages/metadata/generated/schema/entity/services/connections/database/sapHanaConnection.py)] "}` .
I also tried running the Connector externally, it seems to be throwing a similar error:
`Cannot load object from metadata.ingestion.source.database.saphana.connection.get_connection due to cannot import name 'HdbUserStoreConnection' from 'metadata.generated.schema.entity.services.connections.database.sapHanaConnection'`

**To Reproduce**
my OpenMetadata UI configuration:
![image](https://github.com/open-metadata/OpenMetadata/assets/43441555/e60464fd-0840-49bb-bf8f-8b597d1540ee)

my yaml config:
```yaml
source:
  type: sapHana
  serviceName: hana
  serviceConnection:
    config:
      type: SapHana
      connection:        ## Parameters for the SQL Connection
        hostPort: 10.1.x.xxx
        username: xxx
        password: xxx
        databaseSchema: SAPABAP1
  sourceConfig:
    config:
      type: DatabaseMetadata
      markDeletedTables: true
      includeTables: true
      includeViews: true
      includeTags: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO  # DEBUG, INFO, WARNING or ERROR
  openMetadataServerConfig:
    hostPort: "http://10.1.x.xxx:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: "xxx"
    storeServiceConnection: true  # false
```

**Expected behavior**
help to resolve this bug

**Version:**
 - OS: almalinux9.4 / windows11
 - Python version: 3.10/3.9/3.11  all have tried
 - OpenMetadata version: 1.3.4
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[sapHana]==1.3.4`
