### ISSUE TITLE
Non-existing user entry with SAML SSO leads to login loop (should be fixed in 1.4.0 but isn't)

### ISSUE THREAD

**Issue by xenji** [open-metadata/OpenMetadata#16433]
Unfortunately, the bug described in #16076 is still present in 1.4.0. I can provide more details, as offered in the referenced issue.

**Comment by xenji** [comment]
h2. Version response from the API
Can you elaborate on what API you are referring to?

h2. How did you configure the SAML SSO
I replaced some parts with `{...}` for security reasons.

```yaml
authentication:    
      enabled: true
      clientType: public
      provider: "saml"
      saml:
        debugMode: true
        idp:
          entityId: "http://www.okta.com/{...}"
          ssoLoginUrl: "https://{....}.okta.com/app/veevasys_linkdatacatalog_1/{....}/sso/saml"
          idpX509Certificate:
            secretRef: "openmetadata-okta-saml-secret"
            secretKey: "idpX509Certificate"
          authorityUrl: "https://catalog.{...}/api/v1/saml/login"
          nameId: "urn:oasis:names:tc:SAML:2.0:nameid-format:emailAddress"
        sp:
          entityId: "https://catalog.{...}/api/v1/saml/metadata"
          acs: "https://catalog.{...}/api/v1/saml/acs"
          callback: "https://catalog.{...}/saml/callback"
```


h2. How did you deploy the OpenMetadata
* EKS
* External RDS & OpenSearch
* Helm Chart
