### ISSUE TITLE
DBT Ingestion Parsing Error

### ISSUE THREAD

**Issue by mazenorabi** [open-metadata/OpenMetadata#16517]
**Affected module**
Ingestion Framework

**Describe the bug**
When Running DBT Ingestion Externally using local as config type, many errors returned as: `Unexpected exception parsing DBT node due to 'str' object has no attribute 'value'` then the job failed.
![image](https://github.com/open-metadata/OpenMetadata/assets/102815298/24ca6bb8-ddc7-49bb-a6a8-cdc402ff253b)

**To Reproduce**
use below Yaml file (dbt_local_config.yaml) to Run the ingestion-base:1.4.1 image using Kubernetes or Docker Operator:
```
source:
  type: dbt
  serviceName: service_name
  sourceConfig:
    config:
      type: DBT      
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: path/to/catalog.json
        dbtManifestFilePath: path/to/manifest.json
        dbtRunResultsFilePath: path/to/run_results.json
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: dbt
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO  
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    verifySSL: ignore
    securityConfig:
      jwtToken: "*****"
```
The command used inside the Operator is: `cmds=["metadata","ingest","-c","<PATH>/dbt_local_config.yaml"]`

**Expected behavior**
to Ingest DBT Json Files without errors.

**Version:**
 - OS: Linux
 - Python version: 3.10
 - OpenMetadata version: 1.4.1
 - OpenMetadata Ingestion package version:  Airflow 2.8.4 (without OpenMetaData packages)
 - DBT Version: 1.8.1

**Additional context**
- No SSL configuration on OpenMetaData Server.
- Database PostgreSQL 14.
