### ISSUE TITLE
Openmetadata Airflow APIs installation

### ISSUE THREAD

**Issue by wouali** [open-metadata/OpenMetadata#16932]
**Affected module**
Ingestion Framework (Airflow APIs)

**Describe the bug**
openmetadata_managed_apis not effective on a custom Airflow installation (Bitnami chart).

**To Reproduce**

I am deploying an Airflow instance in my kubernetes cluster with the Bitnami Helm chart version `18.3.4` with this values
```yaml

auth:
  username: admin
  existingSecret: "airflow-credentials"

executor: KubernetesExecutor
# Name of an existing ConfigMap with the Airflow config file
existingConfigmap:  ""
extraEnvVars:
- name: AIRFLOW__API__AUTH_BACKENDS
  value:  airflow.api.auth.backend.basic_auth
- name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
  value:  /opt/bitnami/airflow/dag_generated_configs
- name: AIRFLOW__CORE__LAZY_LOAD_PLUGINS
  value:  "False"
- name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
  value:  "False"


web:
  image:
    repository: custom/airflow-image
    tag: 2.9.2
  extraEnvVars:
  - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    value:  "True"


scheduler:
  image:
    repository: custom/airflow-scheduler
    tag: 2.9.2
  automountServiceAccountToken: true


serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false

rbac:
  create: true
  rules: []

postgresql:
  enabled: false

externalDatabase:
  host: "postgresql"
  port: 5432
  user: user_airflow_db
  database: airflow_db
  existingSecret: "postgresql-credentials"
  existingSecretPasswordKey: "postgres_airflow_user_password"

redis:
  enabled:  false
 ```
 
 Airflow web UI custom Dockerfile (identical to the Airflow scheduler except the basic image that would have been `bitnami/airflow-scheduler:2.9.2-debian-12-r0`)

```Dockerfile
FROM docker.io/bitnami/airflow:2.9.2-debian-12-r1

SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]

USER root

RUN apt-get update --yes && \
    apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config && \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN pip install --no-cache-dir \
    openmetadata-ingestion[postgres]==1.4.3 \
    apache-airflow-providers-cncf-kubernetes && \
    pip install --no-cache-dir openmetadata-managed-apis==1.4.3

RUN mkdir -p /opt/bitnami/airflow/dag_generated_configs/ /opt/bitnami/airflow/plugins/

USER 1001
```

**Expected behavior**
Following the Openmetadata [documentation](https://docs.open-metadata.org/v1.4.x/deployment/ingestion/openmetadata) and the above section to reproduce the issue, the steps : 
- install the connector modules
- install the airflow APIs
- configure the Airflow environment
should be done and the `openmetadata_managed_apis` plugin should be effective.

**Version:**
 - Python version: 3.11.9
 - OpenMetadata version: 1.4.3
 - OpenMetadata Ingestion and Airflow APIs package version: 1.4.3
