### ISSUE TITLE
emailConfiguration has email password saved in clear directly in the DB in openmetadata_settings table

### ISSUE THREAD

**Issue by FransDel** [open-metadata/OpenMetadata#17000]
**Affected module**
Configuration saved in DB 

**Describe the bug**
emailConfiguration has the password saved in clear directly in the DB, bad in terms of security. Table : `openmetadata_settings`

**To Reproduce**
We deployed our Open Metadata stack using helm this is the configuration we used 
```yaml 
    smtpConfig:
      enableSmtpServer: true
      openMetadataUrl: <URL>
      serverEndpoint: <EndPoint>
      username: <Username>
      password:
        secretRef: <SecretRef>
        secretKey: <SecretKey>
      transportationStrategy: SMTP_TLS
      supportUrl: <URL>
```

**Expected behavior**
Not having the email password directly accessible in clear in the DB.

**Version:**
 - OS: image used by K8s: openmetadata: docker.getcollate.io/openmetadata/server:1.4.4
 - Python version: image used by K8s: openmetadata: docker.getcollate.io/openmetadata/server:1.4.4
 - OpenMetadata version: 1.4.4
