### ISSUE TITLE
Error:: Superset Ingestion based on Snowflake tables - lineage Error -

### ISSUE THREAD

**Issue by mazenorabi** [open-metadata/OpenMetadata#17360]
**Affected module**
Ingestion Framework

**Describe the bug**
When Running superset ingestion job externally, Dashboard and Tables lineage is not appearing due to the below Error:

```
WARNING  {metadata.Ingestion:status:76} - Error to yield dashboard lineage details for DB service name [service_SNOWFLAKE_DB]: 'Engine' object has no attribute 'fetch_datasource'
```

**service_SNOWFLAKE_DB**: is the snowflake database service name which has been ingested into OpenMetaData already.

The Yaml file looks like this:
```
source:
  type: superset
  serviceName: local_superset
  serviceConnection:
    config:
      type: Superset      
      hostPort: {{ SUPERSET_HOST }}
      connection:
        type: Postgres
        username: {{ USER }}
        authType:
          password: {{ PASSWORD }}
        hostPort: {{ POSTGRESQL_DB }}:5432
        database: superset
  sourceConfig:
    config:
      type: DashboardMetadata
      lineageInformation:
        dbServiceNames:
          - service_SNOWFLAKE_DB
      includeTags: true
      includeDataModels: true
      includeOwners: false
      markDeletedDashboards: true    
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: <HOST>/api
    authProvider: openmetadata
    verifySSL: ignore
    securityConfig:
      jwtToken: "***"
    storeServiceConnection: true
```
dashboards and charts seems like ingested but not the lineage.

**To Reproduce**

Run the ingestion externally using the above Yaml config. 

**Expected behavior**
Ingestion process passed successfully and Lineage between Snowflake tables and dashboard appeared in the UI. 

**Version:**
 - OS: Linux
 - Python version: 3.11
 - OpenMetadata version: 1.4.7
 - OpenMetadata Ingestion package version: 1.4.7
 - Superset Version: 4.0.1
- Superset backend DB Postgresql: 14.10

**Additional context**
Problem reported before as fixed but seems like it isn't [Here](https://github.com/open-metadata/OpenMetadata/discussions/16867)
