### ISSUE TITLE
Automatically created admins don't get profile and displayName updated when using Google SSO

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1781]
If I configure myself as admin, my user is created programmatically when OM starts. When I login into the browser the profile and the displayName are not updated based on the information from Google SSO.

#
Old information was created before Google SSO.
![image](https://user-images.githubusercontent.com/32617/146263527-aecb64ca-5465-4724-b542-4ed0dbeeea67.png)
New information and user promoted to admin after JIT creation of the user.
#
![image](https://user-images.githubusercontent.com/32617/146263555-c4c2391d-cb99-413b-aa00-a87b7b13b23a.png)
#
My configuration.
```
# Authorizer Configuration
authorizerConfiguration:
  className: "org.openmetadata.catalog.security.DefaultCatalogAuthorizer"
  # JWT Filter
  containerRequestFilter: "org.openmetadata.catalog.security.JwtFilter"
  adminPrincipals:
    - "alberto"
  botPrincipals:
    - "ingestion-bot"
  principalDomain: "getcollate.io"
```
