### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by jgrocha** [open-metadata/OpenMetadata#17961]
**Affected module**

Only affects LDAP authentication.

**Describe the bug**

After configuring LDAP authentication, the user name created in the database is: 
`uid=jgr,ou=people,dc=geomaster,dc=pt`.

This user name is compared with the one entered on the login form: `jgr@geomaster.pt`. The strings do not match.

The error is:

```
User with given email exists but is not associated with provider username. Matching User Found By Email [username:email] : [uid=jgr,ou=people,dc=geomaster,dc=pt:jgr@geomaster.pt], Provided User: [jgr:jgr@geomaster.pt]
```

**To Reproduce**

Configure LDAP:

```yaml
ldapConfiguration:
    host: ${AUTHENTICATION_LDAP_HOST:-ldap.geomaster.pt}
    port: ${AUTHENTICATION_LDAP_PORT:-636}
    dnAdminPrincipal: ${AUTHENTICATION_LOOKUP_ADMIN_DN:-"uid=search,ou=Security,dc=geomaster,dc=pt"}
    dnAdminPassword: ${AUTHENTICATION_LOOKUP_ADMIN_PWD:-"xxxxxxx"}
    userBaseDN: ${AUTHENTICATION_USER_LOOKUP_BASEDN:-"dc=geomaster,dc=pt"}
    groupBaseDN: ${AUTHENTICATION_GROUP_LOOKUP_BASEDN:-""}
    roleAdminName: ${AUTHENTICATION_USER_ROLE_ADMIN_NAME:-}
    allAttributeName: ${AUTHENTICATION_USER_ALL_ATTR:-}
    mailAttributeName: ${AUTHENTICATION_USER_MAIL_ATTR:-mail}
    groupAttributeName: ${AUTHENTICATION_USER_GROUP_ATTR:-}
    groupAttributeValue: ${AUTHENTICATION_USER_GROUP_ATTR_VALUE:-}
    groupMemberAttributeName: ${AUTHENTICATION_USER_GROUP_MEMBER_ATTR:-}
    #the mapping of roles to LDAP groups
    authRolesMapping: ${AUTH_ROLES_MAPPING:-""}
    authReassignRoles: ${AUTH_REASSIGN_ROLES:-[]}
    #optional
    maxPoolSize: ${AUTHENTICATION_LDAP_POOL_SIZE:-3}
    sslEnabled: ${AUTHENTICATION_LDAP_SSL_ENABLED:-true}
```
also tried with:
```yaml
    isFullDn: false
    usernameAttributeName: ${AUTHENTICATION_USER_NAME_ATTR:-"uid"}
```

The username created in the database (taken from the json field) is: `uid=jgr,ou=people,dc=geomaster,dc=pt`

This username should be just `jgr`.

**Expected behavior**

If I manually change the json to `{"id": "...", "name": "jgr", "email": "jgr@geomaster.pt",`, the login works.

**Version:**
 - OS: Ubuntu 22.04
 - Python version: Python 3.10.12
 - OpenMetadata version: 1.5.4-release
 - OpenMetadata Ingestion package version:

**Additional context**

I may be missing some configuration variables.

Maybe related with #17452
