### ISSUE TITLE
dbt models with model versions not imported properly

### ISSUE THREAD

**Issue by geoHeil** [open-metadata/OpenMetadata#18116]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

ingestion framework

**Describe the bug**

for dbt with models with model versions such as https://docs.getdbt.com/docs/collaborate/govern/model-versions with the alias enabled https://docs.getdbt.com/docs/collaborate/govern/model-versions#configuring-database-location-with-alias ONLY the mytable_v1 / v2 get the documentation and metadata assigned not the mytable (which would be a view pointing to lateset. I think this might be a bug currently.

**To Reproduce**

have a model with model versions

```
models:
  - name: dim_customers
    latest_version: 1
    config:
      materialized: table
      contract: {enforced: true}
    columns:
      - name: customer_id
        description: This is the primary key
        data_type: int
      - name: country_name
        description: Where this customer lives
        data_type: varchar
    
    # Declare the versions, and highlight the diffs
    versions:
    
      - v: 1
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [country_name]
      
```

the following macro is enabled

```
{% macro create_latest_version_view() %}

    -- this hook will run only if the model is versioned, and only if it's the latest version
    -- otherwise, it's a no-op
    {% if model.get('version') and model.get('version') == model.get('latest_version') %}

        {% set new_relation = this.incorporate(path={"identifier": model['name']}) %}

        {% set existing_relation = load_relation(new_relation) %}

        {% if existing_relation and not existing_relation.is_view %}
            {{ drop_relation_if_exists(existing_relation) }}
        {% endif %}
        
        {% set create_view_sql -%}
            -- this syntax may vary by data platform
            create or replace view {{ new_relation }}
              as select * from {{ this }}
        {%- endset %}
        
        {% do log("Creating view " ~ new_relation ~ " pointing to " ~ this, info = true) if execute %}
        
        {{ return(create_view_sql) }}
        
    {% else %}
    
        -- no-op
        select 1 as id
    
    {% endif %}

{% endmacro %}
```

result:

- table foo_v1
- table foo_v2
- view foo pointing to latest i.e. foo_v2

However, metadata is only ingested for foo_v1, v2 and NOT for foo

**Expected behavior**

Foo should inherit the same metadata as foo_v2 (i.e. latest)

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8] 1.5.6.0
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
