### ISSUE TITLE
Ingestion from S3 to OM

### ISSUE THREAD

**Issue by Diamondra-Rabenaivo** [open-metadata/OpenMetadata#18381]
**Affected module**
Ingestion externally - Connector S3

**Describe the bug**
Context: ingestion from S3 to OM.
Bucket: datalake
Path: 'bfm/change/daily'
Problem: Only the container is ingested, the contents of the container are not.
In my path I have excel files, but I tried with other file types, still nothing.

Here my openmetadata.json file that I've put it on my bucket root.
```
{
    "entries": [
        {
            "dataPath": "bfm/change/journalier",
            "unstructuredFormats": ["*"]
        }
    ]
}
```

Here my config.yaml
```
source:
  type: s3
  serviceName: minioS3
  serviceConnection:
    config:
      type: S3
      awsConfig:
        awsAccessKeyId: *****
        awsSecretAccessKey: ******
        awsRegion: us-east-1
        endPointURL: http://localhost:9000/
  sourceConfig:
    config:
      type: StorageMetadata
      containerFilterPattern:
        includes:
          - datalake
  
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: ****
    storeServiceConnection: true
```
**Expected behavior**
Get list of unstructured file in container in OM
