### ISSUE TITLE
Azure authentication with SPA application does not work

### ISSUE THREAD

**Issue by jgrocha** [open-metadata/OpenMetadata#18865]
**Describe the bug**

Not able to login using Azure SSO.

**To Reproduce**

I've filled the documentation to setup a application on Azure.

![image](https://github.com/user-attachments/assets/06e8cc6e-9a69-458d-a20c-0709b8642d0e)

I've configured `openmetadata.yaml` with:

```yaml
authorizerConfiguration:
  className: ${AUTHORIZER_CLASS_NAME:-org.openmetadata.service.security.DefaultAuthorizer}
  containerRequestFilter: ${AUTHORIZER_REQUEST_FILTER:-org.openmetadata.service.security.JwtFilter}
  adminPrincipals: ${AUTHORIZER_ADMIN_PRINCIPALS:-[admin]}
  principalDomain: ${AUTHORIZER_PRINCIPAL_DOMAIN:-"openmetadata.geomaster.pt"}
  enforcePrincipalDomain: ${AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN:-false}
  enableSecureSocketConnection : ${AUTHORIZER_ENABLE_SECURE_SOCKET:-false}
  useRolesFromProvider: ${AUTHORIZER_USE_ROLES_FROM_PROVIDER:-false}

authenticationConfiguration:
  provider: ${AUTHENTICATION_PROVIDER:-azure}
  publicKeyUrls: ${AUTHENTICATION_PUBLIC_KEYS:-[https://login.microsoftonline.com/common/discovery/keys,https://openmetadata.geomaster.pt/api/v1/system/config/jwks]}
  authority: ${AUTHENTICATION_AUTHORITY:-https://login.microsoftonline.com/26c1aa90-3e3c-4df0-8dc8-66a97018fb32/oauth2/v2.0/authorize}
  clientId: ${AUTHENTICATION_CLIENT_ID:-"e9731a6d-8bec-465a-83c6-e0eb02a04480"}
  callbackUrl: ${OIDC_CALLBACK:-"https://openmetadata.geomaster.pt/callback"}
```

**Expected behavior**

The user should be able to login.

**Version:**
 - OS: Ubuntu 24.04
 - Python version: Python 3.12.3
 - OpenMetadata version: 1.5.5

**Additional context**

I'm managing the Azure and OpenMetadata configurations, so I can change anything on both sides to provide further information.

The MS server returns a token:

![image](https://github.com/user-attachments/assets/b95e4067-37fa-4ee5-826d-4603ca44912e)

But then the next request fails with 401:

![image](https://github.com/user-attachments/assets/68992a06-070d-421a-a305-47858321697e)
