### ISSUE TITLE
Azure SSO callback getRefreshToken null

### ISSUE THREAD

**Issue by beiliubei** [open-metadata/OpenMetadata#19741]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

**Describe the bug**

```
authentication:
      enabled: true
      clientType: "confidential"
      provider: "azure"
      publicKeys:
      - "https://{my domain}/api/v1/system/config/jwks"
      - "https://login.microsoftonline.com/common/discovery/keys"
      authority: "https://login.microsoftonline.com/{my tenant id}"
      clientId: "{my client id}"
      callbackUrl: "https://{my domain}/callback"
      responseType: id_token
      jwtPrincipalClaims:
      - "email"
      - "preferred_username"
      - "sub"
      jwtPrincipalClaimsMapping: []
      # jwtPrincipalClaimsMapping:
      # - username:sub
      # - email:email
      enableSelfSignup: true
      oidcConfiguration:
        enabled: true
        oidcType: "azure"
        clientId:
          secretRef: oidc-secrets
          secretKey: openmetadata-oidc-client-id
        clientSecret:
          secretRef: oidc-secrets
          secretKey: openmetadata-oidc-client-secret
        scope: "openid email profile"
        discoveryUri: "https://login.microsoftonline.com/{my tenant id}/.well-known/openid-configuration"
        useNonce: true
        preferredJwsAlgorithm: RS256
        responseType: code
        disablePkce: true
        callbackUrl: https://{my domain}/callback
        serverUrl: https://{my domain}
        clientAuthenticationMethod: client_secret_post
        tenant: "{my tenant id}"
        maxClockSkew: ""
        tokenValidity: "3600"
```

When use Azure SSO login, after login and redirect to callback url, get this error

**[Auth Callback Servlet] Failed in Auth Login : Cannot invoke "com.nimbusds.oauth2.sdk.token.RefreshToken.getValue()" because the return value of "org.pac4j.oidc.credentials.OidcCredentials.getRefreshToken()" is null**

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

**Version:**
 - Python version:
 - OpenMetadata version: 1.6.3
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**
