### ISSUE TITLE
no database found to handle postgresql

### ISSUE THREAD

**Issue by andrewzah** [open-metadata/OpenMetadata#20037]
**Affected module**
migration (server)

**Describe the bug**
Migration fails with this error:
```
migrate-1  | Migrating the OpenMetadata Schema.
migrate-1  | Failed to db migration due to
migrate-1  | org.flywaydb.core.api.FlywayException: No database found to handle postgresql://openmetadata:openmetadata@postgres:5432/openmetadata?sslmode=disable
```

**To Reproduce**

```yaml
services:
  postgres:
    hostname: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: 'openmetadata'
      POSTGRES_PASSWORD: 'openmetadata'
      POSTGRES_DB: 'openmetadata'
    ports:
      - "5432"

  migrate:
    image: docker.getcollate.io/openmetadata/server:1.6.4
    command: "./bootstrap/openmetadata-ops.sh migrate"
    volumes:
      - "./configs/openmetadata.yaml:/opt/openmetadata/conf/openmetadata.yaml:ro"
```
and the `configs/openmetadata.yaml`:
```
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: org.postgresql.Driver
  # the username and password
  user: openmetadata
  password: openmetadata
  # the JDBC URL; the database is called openmetadata_db
  url: postgresql://openmetadata:openmetadata@postgres:5432/openmetadata?sslmode=disable
  maxSize: ${DB_CONNECTION_POOL_MAX_SIZE:-50}
  minSize: ${DB_CONNECTION_POOL_MIN_SIZE:-10}
  initialSize: ${DB_CONNECTION_POOL_INITIAL_SIZE:-10}
  checkConnectionWhileIdle: ${DB_CONNECTION_CHECK_CONNECTION_WHILE_IDLE:-true}
  checkConnectionOnBorrow: ${DB_CONNECTION_CHECK_CONNECTION_ON_BORROW:-true}
  evictionInterval: ${DB_CONNECTION_EVICTION_INTERVAL:-5 minutes}
  minIdleTime: ${DB_CONNECTION_MIN_IDLE_TIME:-1 minute}
```

**Expected behavior**
I expect the migration to connect to my postgres database and succeed.

**Version:**
 - OpenMetadata version: 1.6.4
