### ISSUE TITLE
Bigquery: Service Connection Config not getting updated properly based on config

### ISSUE THREAD

**Issue by sikumar94** [open-metadata/OpenMetadata#20679]
**Affected module**
Does it impact the UI, backend or Ingestion Framework? - Yes it impacts the Lineage ingestion and service connection on UI

**Describe the bug**
Tested on 1.6.5. I have configured multiple BQ projects as an array, it ingested all the projects' metadata during metadata ingestion. But the connection stored is only the last project. This impacts when pulling the lineage across all projects.
It's only pulling the lineage from one project, as that's the only one stored during store service connection

**To Reproduce**

```
Config used:
source:
  type: bigquery
  serviceName: "bigquery"
  serviceConnection:
    config:
      type: BigQuery
      credentials:
        gcpConfig:
          type: service_account
          projectId: ["project-1","project-2","project-3","project-4"]
          privateKeyId: ""
          privateKey:
          clientEmail: 
          clientId: 
          clientX509CertUrl: 
      taxonomyLocation: "us-central1"
      usageLocation: "us-central1"


  sourceConfig:
    config:
      type: DatabaseMetadata
      includeTables: true
      includeViews: true
      includeTags: true
      includeOwners: true
      includeStoredProcedures: true
      includeDDL: true
sink:
  type: metadata-rest
  config: { }

workflowConfig:
  loggerLevel: "INFO"
  openMetadataServerConfig:
    hostPort: "${OM_API_URL}"
    authProvider: "openmetadata"
    securityConfig:
      jwtToken: "${BOT_JWT_TOKEN}"
    storeServiceConnection: true
```

**Expected behavior**

**Version:**
 - Python version: 3.11
 - OpenMetadata version: [e.g. 1.6.5]
