### ISSUE TITLE
OpenLineage connector cannot find schema name, doesn't elaborate

### ISSUE THREAD

**Issue by orthoxerox** [open-metadata/OpenMetadata#22013]
**Affected module**
Ingestion Framework

**Describe the bug**
When importing information from OpenLineage, the connector doesn't create schemas on its own and doesn't provide any information to debug the issue.

**To Reproduce**

1. Set up a blank OMD instance, a blank PG database, a Kafka broker with `KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true` and a Spark installation with OpenLineage agent, Kafka and PG clients.
```
#Here are the services added to the standard docker-compose-postgres.yml
volumes:
  #...volumes...
  kafka_data:
  pg1-data:
  pg2-data:
#...services...
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    expose:
      - 29092
    ports:
      - "9092:9092"
    networks:
      - app_net
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/bitnami/kafka
  pg1:
    image: postgres
    container_name: pg1
    restart: always
    expose:
      - 5432
    ports:
      - "54321:5432"
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=pg1
    volumes:
      - pg1-data:/var/lib/postgresql/data
  pg2:
    image: postgres
    container_name: pg2
    restart: always
    expose:
      - 5432
    ports:
      - "54322:5432"
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=pg2
    volumes:
      - pg2-data:/var/lib/postgresql/data
```

And a Dockerfile to build Spark in a container (so the hostnames OpenLineage reports match the ones knows by OMD):
```
FROM apache/hadoop:3.3.6
COPY ./spark-3.5.6-bin-hadoop3-scala2.13 /opt/spark
COPY ./openlineage-spark_2.13-1.34.0.jar /opt/hadoop/
COPY ./postgresql-42.7.7.jar /opt/hadoop/
COPY ./kafka-clients-3.4.1.jar /opt/hadoop/
ENV HADOOP_HOME=/opt/hadoop
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:/opt/spark/bin
```
`docker build -t myspark .`

2. Run spark-shell:
```
docker run -it --network openmetadata-docker_app_net myspark bash
spark-shell --master local --jars ./openlineage-spark_2.13-1.34.0.jar,./kafka-clients-3.4.1.jar,./postgresql-42.7.7.jar --conf spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener --conf spark.openlineage.columnLineage.datasetLineageEnabled=true --conf spark.openlineage.transport.type=kafka --conf spark.openlineage.transport.topicName=openlineage.events --conf spark.openlineage.transport.properties.bootstrap.servers=kafka:29092 --conf spark.openlineage.transport.properties.acks=all --conf spark.openlineage.transport.properties.retries=3 --conf spark.openlineage.transport.properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer --conf spark.openlineage.transport.properties.value.serializer=org.apache.kafka.common.serialization.StringSerializer
```
3. Create a new table in PG via Spark:
```scala
spark.range(10).toDF("i").write.
  format("jdbc").
  option("driver", "org.postgresql.Driver").
  option("url", "jdbc:postgresql://pg1:5432/test").
  option("dbtable", "public.source").
  option("user", "postgres").
  option("password", "pg1").
  mode("overwrite").
  save()
```
4. Create a new OpenLineage pipeline service in OMD and point it at the same broker and topic. Run it.
5. It will fail with:
```
[2025-06-27, 09:08:21 UTC] {logger.py:201} INFO - List of failures:
[2025-06-27, 09:08:21 UTC] {logger.py:201} INFO - 
+-------------+---------------+-------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| From        | Entity Name   | Message                                                                             | Stack Trace                                                                                                                                                  |
+=============+===============+=====================================================================================+==============================================================================================================================================================+
| OpenLineage |               | Failed to get fully qualified schema name: Schema FQN not found within services: [] | Traceback (most recent call last):                                                                                                                           |
|             |               |                                                                                     |   File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/pipeline/openlineage/metadata.py", line 263, in get_create_table_request |
|             |               |                                                                                     |     om_schema_fqn = self._get_schema_fqn_from_om(table_details.schema)                                                                                       |
|             |               |                                                                                     |   File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/pipeline/openlineage/metadata.py", line 174, in _get_schema_fqn_from_om  |
|             |               |                                                                                     |     raise FQNNotFoundException(                                                                                                                              |
|             |               |                                                                                     | metadata.ingestion.source.pipeline.openlineage.utils.FQNNotFoundException: Schema FQN not found within services: []                                          |
+-------------+---------------+-------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Expected behavior**
I expect the ingestor to either create the schema for me or to report what schema it is unable to find.

In addition, I am not sure the ingestor even tries to find the right schema: I checked and `_get_schema_fqn_from_om` receives a single string that is `public`. I bet that most Postgres DBs use `public` as their schema, but I don't know if the ingestor actually recognizes the specific DB, it looks to me like the connector iterates through all of them: `services = self.get_db_service_names()`

**Version:**
 - OS: dockerized
 - Python version: whatever is in the container
 - OpenMetadata version: docker.getcollate.io/openmetadata/server:1.8.0
 - OpenMetadata Ingestion package version: docker.getcollate.io/openmetadata/ingestion:1.8.0

**Additional context**
