### ISSUE TITLE
Report Management

### ISSUE THREAD

**Issue by lihan** [open-metadata/OpenMetadata#2323]
I couldn't see any [reports](https://docs.open-metadata.org/openmetadata/schemas/entities/report) samples on the [sandbox](https://sandbox.open-metadata.org/explore/tables) so the below may or may not exist.

## Feature Objectives

* Display the reports generation history. If a report is scheduled on weekly basis. It should display the historical dates if the report was successful or failed.
* Link each report generated to a data asset (CSV on GCS, S3)?
* Link the report generation Airflow pipeline
* Having a button to restart the linked airflow pipeline

**Comment by harshach** [comment]
@lihan Thanks for filing this. We don't have full integration reports yet. Would like to get some details on what constitutes
report in your org. How do you distinguish between a regular airflow pipeline thats doing ETL vs a pipeline thats doing reporting. This will help in classifying them as reports vs pipelines on OM side. Similarly what are some of the interesting metadata about reports that you would like capture apart from run-time history

**Comment by sureshms** [comment]
@lihan, another question for reports is - is there a service/system where reports are created. As an example, dashboard service such as Looker, Superset, etc. are places where dashboard is created and we capture the relationship dashboard service contains charts and dashboards. Do you have a system where people write queries and create reports from them?

**Comment by lihan** [comment]
@sureshms We use a mixture of Redash and Google Data Studio for purely dashboard. But they are for dashboard purpose, not relate to the reports. Reports generally mean they need to be shared with a third party.

Yes, we do have a system for BIs / Data Engineers to add reports, it's in-house developed. That system has no UI, it's git version controlled bunch of yaml files.

Each yaml file contains the steps to create an Airflow pipeline. Example below
```
name: partner_report
schedule: "0 1 1 * *"  # Run every month
tasks:
# Register or update Report to OpenMetadata via API

  - operator: run_bq_sql
              sql: CREATE OR REPLACE TABEL  AS ....
  - operator: export_bq_table_to_gcs
          table: table_name
  - operator: email_notifications
       recipients: '...'
      attachments: ......

# Add new operator here to push above stats to Openmetadata via API
 
```
