### ISSUE TITLE
[UI] [Backend] OpenMetadata UI breaks when passing multiple principalDomains during InitialAdminCreation

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#3757]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI, Backend

**Describe the bug**
If we set multiple principalDomains in openmetadata.yaml config for authorizerConfiguration section, this breaks UI post SSO Login with API's erroring out to get loggedInUsers and User Details.

**To Reproduce**

OpenMetadata.yaml
```yaml
...
authorizer:
  className: "org.openmetadata.catalog.security.DefaultAuthorizer"
  containerRequestFilter: "org.openmetadata.catalog.security.JwtFilter"
  initialAdmin: "akash"
  botPrincipal: "ingestion-bot"
  principalDomain: "abc.org, xyz.org"
...
```

Run the openmetadata Server up. Try to Single Sign On.

**Expected behavior**
It should allow me to sign in with akash@abc.org or akash@xyz.org and be admin.

**Actual Behaviour**
UI breaks as Server response with 400 Bad Request for getLoggedInUser endpoint and UI shows only loading icon.

Request URL: https://hostname/api/v1/users/loggedInUser?fields=profile,teams,roles

```json
{
  “code”: 400,
  “message”: “[email must match \“^\\S+@\\S+\\.\\S+$\“]”
}
```

**Version:**
 - OpenMetadata version: [e.g. 0.8] 0.9.0

**Additional context**
This bug was reported by community user [here](https://openmetadata.slack.com/archives/C02B6955S4S/p1648620714282259).

cc - @harshach , @sureshms
