### ISSUE TITLE
OpenMetadata YAML configuration for Airflow Connectivity in Secure Mode (Okta,Auth0,Azure)

### ISSUE THREAD

**Issue by akash-jain-10** [open-metadata/OpenMetadata#4060]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI, backend.

**Describe the bug**
Currently, our Airflow Configuration only supports Google SSO via secretKey, authProvider configuration in openmetadata.yaml.
We will also need to support other Authentication Providers (Okta, Auth0, Azure) with the similar config for successfully creating Ingestions from UI.
https://github.com/open-metadata/OpenMetadata/blob/d49defcd77d820a712dd94bf125bd080ac4dc1cf/conf/openmetadata.yaml#L156

Here are some sample configs to be expected -

Airflow Azure Auth - 

```yaml
airflowConfiguration:
  apiEndpoint: http://${AIRFLOW_HOST:-localhost}:${AIRFLOW_PORT:-8080}
  username: ${AIRFLOW_USERNAME:-admin}
  password: ${AIRFLOW_PASSWORD:-admin}
  metadataApiEndpoint: http://${SERVER_HOST:-localhost}:${SERVER_PORT:-8585}/api
  authProvider: "azure"
  client_id: "Client ID"
  client_credential: "Secret Key"
  authority: "Authority"
  scopes: 
  - "Scope1"
  - "Scope2"
```

Airflow Okta Auth -

```yaml
airflowConfiguration:
  apiEndpoint: http://${AIRFLOW_HOST:-localhost}:${AIRFLOW_PORT:-8080}
  username: ${AIRFLOW_USERNAME:-admin}
  password: ${AIRFLOW_PASSWORD:-admin}
  metadataApiEndpoint: http://${SERVER_HOST:-localhost}:${SERVER_PORT:-8585}/api
  authProvider: "okta"
  clientId: "Client ID"
  privateKey: "Secret Key"
  orgUrl: "OrgUrl"
  scopes: 
  - "Scope1"
  - "Scope2"
```

Airflow Auth0 Auth -

```yaml
airflowConfiguration:
  apiEndpoint: http://${AIRFLOW_HOST:-localhost}:${AIRFLOW_PORT:-8080}
  username: ${AIRFLOW_USERNAME:-admin}
  password: ${AIRFLOW_PASSWORD:-admin}
  metadataApiEndpoint: http://${SERVER_HOST:-localhost}:${SERVER_PORT:-8585}/api
  authProvider: "auth0"
  clientId: "Client ID"
  secretKey: "Secret Key"
  domain: "domain"
```
