### ISSUE TITLE
Automatically publish Docker Images

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#5029]
Prepare a github action capable of building, tagging and publishing all new docker images after a release or when a bugfix/patch is required on demand

**Comment by harshach** [comment]
@akash-jain-10 @Vj-L ^

**Comment by akash-jain-10** [comment]
This is partially done for release! we need to update CI to make is run on BugFix and Patches!

**Comment by pmbrull** [comment]
@akash-jain-10 we might just need to add something like

```
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag being built"
```
