### ISSUE TITLE
Seeing "Invalid UUID string: name" when using Custom OIDC

### ISSUE THREAD

**Issue by HumairAK** [open-metadata/OpenMetadata#5224]
Using [Dex OIDC](https://github.com/dexidp/dex) as the oidc provider (with [openshift connector](https://dexidp.io/docs/connectors/openshift/)).
Deployed OpenMetadata on Kubernetes (actually Openshift, but it shouldn't make a difference here I think.) 

OpenMetadata accessible at: https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org

In my dex oidc config I have configured the following client: 

```yaml
      - id: openmetadata
        name: OpenMetadata Service
        redirectURIs:
          - https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org/callback
        secretEnv: OPENMETADATA_SECRET
```

In OpenMetadata deployment I've set the following env vars:

```
          env:
            - name: AUTHENTICATION_PROVIDER
              value: custom-oidc
            - name: AUTHENTICATION_PUBLIC_KEYS
              value: '[https://dex-dex.apps.odh-cl1.apps.os-climate.org/keys]'
            - name: AUTHENTICATION_AUTHORITY
              value: "https://dex-dex.apps.odh-cl1.apps.os-climate.org"
            - name: AUTHENTICATION_CLIENT_ID
              value: openmetadata
            - name: AUTHENTICATION_CALLBACK_URL
              value: https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org/callback
            - name: AUTHORIZER_CLASS_NAME
              value: org.openmetadata.catalog.security.DefaultAuthorizer
            - name: AUTHORIZER_REQUEST_FILTER
              value: org.openmetadata.catalog.security.JwtFilter
            - name: AUTHORIZER_ADMIN_PRINCIPALS
              value: '[HumairAK]'
            - name: AUTHORIZER_INGESTION_PRINCIPALS
              value: '[ingestion-bot]'
            - name: AUTHORIZER_PRINCIPAL_DOMAIN
              value: open-metadata.org
``` 

OIDC Configuration info: https://dex-dex.apps.odh-cl1.apps.os-climate.org/.well-known/openid-configuration

I'm able to to sign in  https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org via the custom oidc, but as soon as dex redirects to openmetadata things seem to awry, the callback to `https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org/callback` fails: 

```
Request URL: https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org/callback
Request Method: GET
Status Code: 404 Not Found
```
and there seems to be a `400 bad request` to `api/v1/user` : 

```
Request URL: https://openmetadata-openmetadata.apps.odh-cl1.apps.os-climate.org/api/v1/users/name/?fields=profile,teams,roles
Request Method: GET
Status Code: 400 Bad Request
```

Resulting in the following console log: `Invalid UUID string: name` in the ui. 
Any ideas?
