### ISSUE TITLE
Errors in Profiler (Sample Data)

### ISSUE THREAD

**Issue by flowy0** [open-metadata/OpenMetadata#6055]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
Ingestion Profiler

**Describe the bug**
Got this error when running `metadata profile -c hive_profiler.yaml`

hive_profiler.yaml (with masked fields)
```
source:
    type: hive
    serviceName: test_hive1
    serviceConnection:
      config:
        type: Hive
        hostPort: host:10000
        username: user
        password: pass
        databaseSchema: db1
        connectionArguments:
          auth: LDAP
    sourceConfig:
      config:
        type: Profiler
        generateSampleData: true
        fqnFilterPattern:
          includes: ["test_hive1.default.db1.generic_food"]
  processor:
    type: orm-profiler
    config:
      test_suite:
        name: My Test Suite
        tests:
          - table: test_hive1.db1.table1
            profile_sample_query: SELECT * from db1.table1 LIMIT 10
  sink:
    type: metadata-rest
    config: {}
  workflowConfig:
    openMetadataServerConfig: 
          hostPort: https://host/api
          authProvider: google
          securityConfig:
              secretKey: openmetadata-sa-key.json
              audience: https://www.googleapis.com/oauth2/v4/token
```

```
[2022-07-12 17:49:00] INFO     {Ingestion:database_service:164} - Scanned [test_hive1.default.db1.generic_food]
[2022-07-12 17:49:52] INFO     {Profiler:metadata_rest:103} - Successfully ingested profiler & test data for test_hive1.default.db1.generic_food
[2022-07-12 17:49:52] INFO     {Ingestion:database_service:164} - Scanned [test_hive1.default.db1.generic_food_2016210263]
[2022-07-12 17:50:36] ERROR    {ORM Profiler Workflow:orm_profiler:574} - Could not obtain sample data from generic_food_2016210263 - unsupported format character '%' (0x25) at index 289
[2022-07-12 17:50:36] INFO     {Profiler:metadata_rest:103} - Successfully ingested profiler & test data for test_hive1.default.db1.generic_food_2016210263

```
**To Reproduce**

Screenshots or steps to reproduce

Run `metadata profile -c hive_profiler.yaml`

**Expected behavior**
Ingest sample data without error 

**Version:**
 - OS:  : MacOS
 - Python version: 3.9
 - OpenMetadata version: 0.11.1
 - OpenMetadata Ingestion package version: `openmetadata-ingestion[docker]==0.11.1

**Additional context**
Slack Thread: https://openmetadata.slack.com/archives/C02B6955S4S/p1657013791343369

**Comment by flowy0** [comment]
Just to add, there were 2 tables matching the regex.
1. generic_food
2. generic_food_2016210263

There are no errors if i specify the profiler like this:
```
processor:
  type: "orm-profiler"
  config:
    test_suite:
      name: My Test Suite
      tests:
        - table: test_hive1.default.db1.generic_food
          profile_sample_query: SELECT * from db1.generic_food LIMIT 10
        - table: test_hive1.default.db1.generic_food_2016210263
          profile_sample_query: SELECT * from db1.generic_food_2016210263 LIMIT 10
```
