### ISSUE TITLE
Google SSO - Authenticated user switch to anonymous

### ISSUE THREAD

**Issue by haithem-souala** [open-metadata/OpenMetadata#6132]
**Affected module**
- Authentication
- Google SSO

**Describe the bug**
User automatically switch to anonymous

**To Reproduce**
- Authenticate using Google SSO
- Go to any page or at home page, refresh the page
- Authenticated user will be switched automatically to anonymous

Screenshots or steps to reproduce
1 - 
![Capture d’écran 2022-07-17 à 22 20 50](https://user-images.githubusercontent.com/75131226/179423510-02d7a3d9-7e90-4ce1-8e19-6c1858ebc9bf.png)

2 - 
![Capture d’écran 2022-07-17 à 22 21 20](https://user-images.githubusercontent.com/75131226/179423530-eecdc8fb-2dc7-4876-9b60-1f226fe5ebc5.png)

3 -
![Capture d’écran 2022-07-17 à 22 21 41](https://user-images.githubusercontent.com/75131226/179423540-12a1ee30-a610-4d14-88b4-658f19505781.png)

**Expected behavior**

**Version:**
 - OS: Linux
 - OpenMetadata version: 1.11.1

**Additional context**

**Comment by vivekratnavel** [comment]
Hi @haithem-souala, I am unable to reproduce this issue. Can you please give more details about your environment? I would like to know which Linux OS you are running and which browser you are able to reproduce this. 

Also, it would be great if you can let me know if you are able to reproduce this issue accessing the sandbox - https://sandbox.open-metadata.org/

**Comment by haithem-souala** [comment]
OM deployed on GKE
ES, ingestion and Mysql on GCE
They both share the same VPC

I'am not able to reproduce this issue on the sandbox.


This is the applied  value file:
```
# Default values for OpenMetadata.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# Overrides the openmetadata config file with the help of Environment Variables
# Below are defaults as per openmetadata-dependencies Helm Chart Values
global:
  # Values can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  logLevel: INFO
  openmetadata:
    host: openmetadata
    port: 8585
    adminPort: 8586
  elasticsearch:
    host: IP_REDACTED
    port: 9200
    scheme: http
    connectionTimeoutSecs: 5
    socketTimeoutSecs: 60
    batchSize: 10
    trustStore:
      enabled: false
      path: ""
      password:
        secretRef: "elasticsearch-truststore-secrets"
        secretKey: "openmetadata-elasticsearch-truststore-password"
    auth:
      enabled: false
      username: "elasticsearch"
      password:
        secretRef: elasticsearch-secrets
        secretKey: openmetadata-elasticsearch-password
  database:
    host: IP_REDACTED
    port: 3306
    driverClass: com.mysql.cj.jdbc.Driver
    dbScheme: mysql
    dbUseSSL: false
    databaseName: openmetadata_db
    auth:
      username: openmetadata_user
      password:
        secretRef: mysql-secrets
        secretKey: openmetadata-mysql-password
  airflow:
    enabled: true
    # endpoint url for airflow
    host: http://IP_REDACTED:8080
    auth:
      username: admin
      password:
        secretRef: airflow-secrets
        secretKey: openmetadata-airflow-password
    openmetadata:
      # possible values are "no-auth", "azure", "google", "okta", "auth0", "custom-oidc", "openmetadata"
      authProvider: "no-auth"
      # this will be the api endpoint url of OpenMetadata Server
      serverHostApiUrl: "http://openmetadata.openmetadata.svc.cluster.local:8585/api"
      authConfig:
        azure:
          clientSecret:
            secretRef: azure-client-secret
            secretKey: azure-client-secret
          authority: ""
          scopes: []
          clientId: ""
        google:
          # absolute path of secret file on airflow instance
          secretKeyPath: ""
          audience: "https://www.googleapis.com/oauth2/v4/token"
        okta:
          clientId: ""
          orgUrl: ""
          privateKey:
            secretRef: okta-client-private-key-secret
            secretKey: okta-client-private-key-secret
          email: ""
          scopes: []
        auth0:
          clientId: ""
          secretKey:
            secretRef: auth0-client-key-secret
            secretKey: auth0-client-key-secret
          domain: ""
        customOidc:
          clientId: ""
          secretKey:
            secretRef: custom-oidc-key-secret
            secretKey: custom-oidc-key-secret
          tokenEndpoint: ""
        openMetadata:
          jwtToken:
            secretRef: openmetadata-jwt-secret
            secretKey: openmetadata-jwt-secret
  authorizer:
    className: "org.openmetadata.catalog.security.NoopAuthorizer"
    containerRequestFilter: "org.openmetadata.catalog.security.NoopFilter"
    initialAdmins:
    - "haithem.souala@melting-point.fr"
    - "admin"
    botPrincipals:
    - "ingestion-bot"
    principalDomain: "meta.services.woopit.fr"
    enforcePrincipalDomain: false
    enableSecureSocketConnection: false
  authentication:
    provider: "google"
    publicKeys:
      - "https://www.googleapis.com/oauth2/v3/certs"
    authority: "https://accounts.google.com"
    clientId: "XXXXXXXXXX-XXXXXXXXXrigac9v6cang0bf6bls.apps.googleusercontent.com"
    callbackUrl: "https://meta.services.woopit.fr/callback"
  jwtTokenConfiguration:
    enabled: false
    # File Path on Airflow Container
    rsapublicKeyFilePath: ""
    # File Path on Airflow Container
    rsaprivateKeyFilePath: ""
    jwtissuer: "open-metadata.org"
    keyId: "Gb389a-9f76-gdjs-a92j-0242bk94356"

  # Example Google SSO Auth Config
  # authorizer:
  #   className: "org.openmetadata.catalog.security.DefaultAuthorizer"
  #   containerRequestFilter: "org.openmetadata.catalog.security.JwtFilter"
  #   initialAdmins:
  #   - "suresh"
  #   botPrincipal:
  #   - "ingestion-bot"
  #   principalDomain: "open-metadata.org"
  # authentication:
  #   provider: "google"
  #   publicKeys:
  #   - "https://www.googleapis.com/oauth2/v3/certs"
  #   authority: "https://accounts.google.com"
  #   clientId: "<client_id>"
  #   callbackUrl: "<callback_url>"


image:
  repository: openmetadata/server
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.11.1"
  pullPolicy: "Always"

sidecars: []
# - name: "busybox"
#   image: "busybox:1.34.1"
#   imagePullPolicy: "Always"
#   command: ["ls"]
#   args: ["-latr", "/usr/share"]
#   env:
#   - name: DEMO
#     value: "DEMO"
#   volumeMounts:
#   - name: extras
#     mountPath: /usr/share/extras
#     readOnly: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "openmetadata"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 100

service:
  type: ClusterIP
  port: 8585
  adminPort: 8586
  annotations: {}

extraEnvs: []
# - name: MY_ENVIRONMENT_VAR
#   value: the_value_goes_here

extraVolumes: []
# - name: extras
#   emptyDir: {}

extraVolumeMounts: []
# - name: extras
#   mountPath: /usr/share/extras
#   readOnly: true

extraInitContainers: []

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5

```

**Comment by haithem-souala** [comment]
```
# Source: openmetadata/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmetadata
  labels:
    helm.sh/chart: openmetadata-0.0.28
    app.kubernetes.io/name: openmetadata
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "0.11.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx-main
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "meta.services.woopit.fr"
      secretName: meta.services.woopit.fr-tls
  rules:
    - host: "meta.services.woopit.fr"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: openmetadata
                port:
                  number: 8585
```
