### ISSUE TITLE
Error deploying openmetadata on Kind cluster

### ISSUE THREAD

**Issue by revit13** [open-metadata/OpenMetadata#6324]
I deployed openmetadata on Kind cluster following: https://docs.open-metadata.org/deploy/deploy-on-kubernetes ;
the deployment seems to be ok as the pods are in running state but when creating a connection to mysql and testing it I get the following error: `Airflow Exception [Failed to test connection.] due to [null].`

kind v0.14.0 go1.18.2 linux/amd64 

details of the deployment:

```
brew install kind (MacOS)
kind create cluster
kubectl apply -f pv1.yaml
kubectl apply -f pv2.yaml
kubectl create secret generic airflow-mysql-secrets --from-literal=airflow-mysql-password=airflow_pass
helm install openmetadata-dependencies open-metadata/openmetadata-dependencies --values values-deps.yaml
kubectl create secret generic mysql-secrets --from-literal=openmetadata-mysql-password=openmetadata_password
kubectl create secret generic airflow-secrets --from-literal=openmetadata-airflow-password=admin
helm install openmetadata open-metadata/openmetadata
```

pv1.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag
  labels:
    app: dag
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef: # the claimRef is here to provide a "connection" between this pv and the pvc.
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: dag 
    namespace: default
  hostPath:
    path: /tmp/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag
  namespace: default
  labels:
    app: dag
spec:
        #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 1Gi

```

pv2.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  labels:
    app: logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef: # the claimRef is here to provide a "connection" between this pv and the pvc.
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: logs
    namespace: default
  hostPath:
    path: /tmp/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: default
  labels:
    app: logs
spec:
        #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 1Gi
```

values-deps.yaml
```
# Default values for deps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MQSQL configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  fullnameOverride: "mysql"
  image:
    pullPolicy: "Always"
  auth:
    rootPassword: password    # provided by CI/CD
  primary:
    service:
      nodePort: 3306
  initdbScripts:
    init_openmetadata_db_scripts.sql: |
      CREATE DATABASE openmetadata_db;
      CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'openmetadata_password';
      GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
      commit;
    init_airflow_db_scripts.sql: |
      CREATE DATABASE airflow_db;
      CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
      GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
      commit;

# ElasticSearch configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/elastic/elasticsearch
elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  fullnameOverride: "elasticsearch"
  imagePullPolicy: "Always"
  esJavaOpts: "-Xmx128m -Xms128m"
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=20s"
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "1000m"
      memory: "1024M"

# Airflow configurations for helm dependency
# you can find more details about this here https://github.com/airflow-helm/charts
airflow:
  enabled: true
  airflow:
    image:
      repository: openmetadata/airflow
      tag: 0.11.1
      pullPolicy: "IfNotPresent"
    executor: "KubernetesExecutor"
    config:
      # This is required for OpenMetadata UI to fetch status of DAGs
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      # OpenMetadata Airflow Lineage Backend Configurations
      AIRFLOW__LINEAGE__BACKEND: airflow_provider_openmetadata.lineage.openmetadata.OpenMetadataLineageBackend
      AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME: airflow_helm
      AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT: http://openmetadata.default.svc.cluster.local:8585/api
      AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE: no-auth
      # OpenMetadata Airflow Apis Plugin DAGs Configuration
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_RUNNER_TEMPLATE: "/opt/airflow/dag_templates/dag_runner.j2"
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dags"
    users:
    - username: admin
      password: admin
      role: Admin
      email: spiderman@superhero.org
      firstName: Peter
      lastName: Parker
  web:
    readinessProbe:
      enabled: true
      initialDelaySeconds: 360
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 360
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 10
  postgresql:
    enabled: false
  workers:
    enabled: false
  flower:
    enabled: false
  redis:
    enabled: false
  externalDatabase:
    type: mysql
    host: mysql.default.svc.cluster.local
    port: 3306
    database: airflow_db
    user: airflow_user
    passwordSecret: airflow-mysql-secrets
    passwordSecretKey: airflow-mysql-password
  serviceAccount:
    create: true
    name: "airflow"
  dags:
    persistence:
      enabled: true
      existingClaim: dag
      # NOTE: "" means cluster-default
      #storageClass: "manual"
      accessMode: ReadWriteMany
      size: 1Gi
  logs:
    persistence:
      enabled: true
      existingClaim: logs
      # empty string means cluster-default
      #storageClass: "manual"
      accessMode: ReadWriteMany
      size: 1Gi

```
it might take a while for the deployment to be ready.
then port forward openmetadata 

kubectl port-forward <openmetadata-front end pod name> 8585:8585
```
open browser in localhost:8585 and go to services->database service -> mysql
and enter:

For testing connectivity, I used the mysql instance that gets created as part of openmetadata-dependencies helm with
hostAndPort as mysql.default.svc.cluster.local:3306
username as openmetadata_user
password as openmetadata_password
database schema as openmetadata_db
```
