### ISSUE TITLE
modify `gcsConfig` to add ADC support for bigquery 

### ISSUE THREAD

**Issue by ulixius9** [open-metadata/OpenMetadata#7030]
**Affected module**
Ingestion Framework

**Describe the bug**
In the previous release the Bigquery ADC was working by passing the following config
```
...
serviceConnection:
    config:
      type: BigQuery
      credentials:
        gcsConfig: {}
...
```

Since on the latest main made all the filed for `GCSValues` required, the same config throws validation error.

**Expected behavior**
Create a new type in `gcsConfig` to support GCP ADC
