### ISSUE TITLE
Profiler ingestion does not fail if the connection cannot be established

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7278]
**Affected module**
Ingestion Framework

**Describe the bug**
Profiler ingestion does not fail if the connection cannot be established. 

**To Reproduce**
- Start OM with PostgreSQL
- Create an ingestion workflow for the airflow DB with the following configuration
```
source:
  type: postgres
  serviceName: local_postgres_airflow
  serviceConnection:
    config:
      type: Postgres
      username: airflow_user
      password: airflow_pass
      hostPort: localhost:5432
      database: airflow_db
  sourceConfig:
    config:
      type: DatabaseMetadata
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: no-auth
```
- Create a profile ingestion

**Expected behavior**
The ingestion should fail since the connection to `localhost:5432` is impossible.

**Version:**
 - OpenMetadata version: 0.12

cc: @TeddyCr
