### ISSUE TITLE
`Object of type 'memoryview' is not JSON serializable` when ingesting sample data with PostgreSQL

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#7280]
**Affected module**
Ingestion Framework

**Describe the bug**
The error `Object of type 'memoryview' is not JSON serializable` appears in some tables when ingesting sample data with PostgreSQL.

**To Reproduce**

- Start OM with PostgreSQL
- Create an ingestion workflow for the airflow DB with the following configuration
```
source:
  type: postgres
  serviceName: local_postgres_airflow
  serviceConnection:
    config:
      type: Postgres
      username: airflow_user
      password: airflow_pass
      hostPort: localhost:5432
      database: airflow_db
  sourceConfig:
    config:
      type: DatabaseMetadata
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: no-auth
```
- Create a profile ingestion with Ingest Sample Data enabled
- Run the ingestion

These errors are displayed in the logs:

- `Error trying to PUT sample data for local_postgres_airflow.airflow_db.public.session: Object of type 'memoryview' is not JSON serializable`
- `Error trying to PUT sample data for local_postgres_airflow.airflow_db.public.task_instance: Object of type 'memoryview' is not JSON serializable`
- `Error trying to PUT sample data for local_postgres_airflow.airflow_db.public.dag_run: Object of type 'memoryview' is not JSON serializable`

![image](https://user-images.githubusercontent.com/11074908/188727492-90c2dd92-85da-4ce6-89c3-20a89f846691.png)

**Expected behavior**

It should ingest sample data for all tables without errors.

**Version:**
 - OpenMetadata version: 0.12

cc @TeddyCr
