### ISSUE TITLE
OpenMetadata Not Working With Postgres

### ISSUE THREAD

**Issue by SUMITGANGWAR** [open-metadata/OpenMetadata#7326]
Hi,

When I run docker-compose-postgres.yml file then OMD not up and running and when I check logs for Openmetadata Server then It show trying to connect mysql:3306 not postgres.

I am attaching screenshot of It.
![Screenshot from 2022-09-08 12-06-41](https://user-images.githubusercontent.com/54278702/189052553-222700aa-e186-410a-bddb-96661e9aa3a5.png)
![Screenshot from 2022-09-08 12-07-09](https://user-images.githubusercontent.com/54278702/189052559-84021d22-1dd4-4a7f-9b3f-644e0c69efb6.png)

**Comment by harshach** [comment]
@SUMITGANGWAR please change the database to below
```
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: ${DB_DRIVER_CLASS:-org.postgresql.Driver}
  # the username and password
  user: ${MYSQL_USER:-postgres}
  password: ${MYSQL_USER_PASSWORD:-4y7sV96vA9wv46VR}
  # the JDBC URL; the database is called openmetadata_db
  url: jdbc:${DB_SCHEME:-postgresql}://${MYSQL_HOST:-localhost}:${MYSQL_PORT:-5432}/${MYSQL_DATABASE:-openmetadata_db}?allowPublicKeyRetrieval=true&useSSL=${DB_USE_SSL:-false}&serverTimezone=UTC
```

you can export DB_DRIVER_CLASS="org.postgresql.Driver"
