### ISSUE TITLE
Support K8s Secret for storing public and private keys used by JWT Token feature

### ISSUE THREAD

**Issue by ehausig** [open-metadata/OpenMetadata#7677]
Enabling JWT Tokens for OpenMetadata 0.12.0 requires mounting public and private keys to the container's file system in a DER (binary) format. In a Kubernetes environment, securables such as private keys should be stored as Secrets. While a K8s Secret can be mounted to a container's file system as a file, it cannot be created from a binary file without first encoding the file's contents as a string (e.g. Base64.) Unfortunately, this approach does not work for OpenMetadata because the application expects the file to be in the DER (binary) format, not a Base64-encoded  DER binary.

The `openmetadata.yaml` currently (0.12.0) uses the following variables to reference the paths of the public and private key files:
```
jwtTokenConfiguration:
  rsapublicKeyFilePath: ${RSA_PUBLIC_KEY_FILE_PATH:-"/openmetadata/conf/public_key.der"}
  rsaprivateKeyFilePath: ${RSA_PRIVATE_KEY_FILE_PATH:-"/openmetadata/conf/private_key.der"}
```

## Suggestion 1

One approach to solving the problem would be to allow the user to provide the public and private keys as Base64 values via two new environment variables (e.g. `RSA_PUBLIC_KEY` and `RSA_PRIVATE_KEY`.) In this case, the `openmetadata.yaml` could implement two new configs:

```
jwtTokenConfiguration:
  rsapublicKeyFilePath: ${RSA_PUBLIC_KEY_FILE_PATH:-"/openmetadata/conf/public_key.der"}
  rsaprivateKeyFilePath: ${RSA_PRIVATE_KEY_FILE_PATH:-"/openmetadata/conf/private_key.der"}

  # new configs
  rsapublicKey: ${RSA_PUBLIC_KEY:-""}
  rsaprivateKey: ${RSA_PRIVATE_KEY:-""}
```

The user could generate new public and private keys using `openssl`. However, they would also need to Base64-encode the values so that each key could be embedded into a Kubernetes Secret and easily mapped to environment variables:
```
# generate the keys
openssl genrsa -out key.pem 2048
openssl rsa -in key.pem -pubout > key.pub
base64 key.pem > private_key.b64
base64 key.pub > public_key.b64

# create the K8s secret from the newly-created keys
kubectl create secret generic openmetadata-jwt-keys --from-file=private_key=private_key.b64,public_key=public_key.b64
```

(Note that the keys are converted to Base64 so that they do not contain any escape characters, otherwise there can be problems when exporting the strings to env vars.)

The user would then map the secrets to the new `RSA_PUBLIC_KEY` and `RSA_PRIVATE_KEY` environment variables in the Helm chart's `values.yaml` file. For example:
```
extraEnvs:
  - name: RSA_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: openmetadata-jwt-keys
        key: public_key
  - name: RSA_PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: openmetadata-jwt-keys
        key: private_key
```

In this scenario, OpenMetadata would need to be modified to support Base64-decoding the keys from the `RSA_PUBLIC_KEY` and `RSA_PRIVATE_KEY` environment variables.

## Suggestion 2

Another approach to solving the problem might be to simply support the text-based versions of the keys. In this case, the keys are generated just as before but imported directly into the K8s Secret:
```
# generate the keys
openssl genrsa -out key.pem 2048
openssl rsa -in key.pem -pubout > key.pub

# create the K8s secret from the newly created keys
kubectl create secret generic openmetadata-jwt-keys --from-file=private_key=key.pem,public_key=key.pub
```

(Note that in this case, the keys remain in their original text format because they will be subsequently mounted as files.)

The user could then mount the keys to the file system of the container via the Helm chart's `values.yaml` file. For example:
```
extraVolumes:
  - name: private-key
    secret:
      secretName: openmetadata-jwt-keys
      items:
        - key: private_key
          path: key.pem
  - name: public-key
    secret:
      secretName: openmetadata-jwt-keys
      items:
        - key: public_key
          path: key.pub

extraVolumeMounts:
  - name: private-key
    mountPath: "/etc/openmetadata/keys/private"
    readOnly: true
  - name: public-key
    mountPath: "/etc/openmetadata/keys"
    readOnly: true

```

The user could then update the `jwtTokenConfiguration` paths in the Helm chart to use the "text versions" of the public and private keys. For example:
```
  jwtTokenConfiguration:
    enabled: true
    rsapublicKeyFilePath: "/etc/openmetadata/keys/key.pub"
    rsaprivateKeyFilePath: "/etc/openmetadata/keys/private/key.pem"
    jwtissuer: "open-metadata.org"
    keyId: "Gb389a-9f76-gdjs-a92j-0242bk94356"
```

In this scenario, OpenMetadata would need to be modified to support both the DER and PEM formats of keys in its `openmetadata.yaml` file:
```
jwtTokenConfiguration:
  rsapublicKeyFilePath: ${RSA_PUBLIC_KEY_FILE_PATH:-"/openmetadata/conf/public_key.der"} # <<< support PEM or DER
  rsaprivateKeyFilePath: ${RSA_PRIVATE_KEY_FILE_PATH:-"/openmetadata/conf/private_key.der"} # <<< support PEM or DER
```

**Comment by ehausig** [comment]
This is a bit embarrassing, but I learned something new about K8s. I was able to successfully create a secret using the DER (binary) files and mount them to the container, so I don't think anything needs to be changed/added to OpenMetadata to get it work with K8s.

In short, here is what worked for me:

1. Generate a public/private key pair (per the docs):
```
openssl genrsa -out private_key.pem 2048
openssl pkcs8 -topk8 -inform PEM -outform DER -in private_key.pem -out private_key.der -nocrypt
openssl rsa -in private_key.pem -pubout -outform DER -out public_key.der
```

2. Create a K8s secret directly from the DER files like this:
```
kubectl create secret generic openmetadata-jwt-keys --from-file=private_key=private_key.der,public_key=public_key.der
```

3. Add the following volumes and volume mounts to the values.yaml file of the Helm chart:
```
extraVolumes:
  - name: private-key
    secret:
      secretName: openmetadata-jwt-keys
      items:
        - key: private_key
          path: private_key.der
  - name: public-key
    secret:
      secretName: openmetadata-jwt-keys
      items:
        - key: public_key
          path: public_key.der

extraVolumeMounts:
  - name: private-key
    mountPath: "/etc/openmetadata/keys/private"
    readOnly: true
  - name: public-key
    mountPath: "/etc/openmetadata/keys"
    readOnly: true
```

4. Update the jwtTokenConfiguration section of the Helm chart to reference the paths of the mounted DER files:
```
  jwtTokenConfiguration:
    enabled: true
    rsapublicKeyFilePath: "/etc/openmetadata/keys/public_key.der"
    rsaprivateKeyFilePath: "/etc/openmetadata/keys/private/private_key.der"
    jwtissuer: "foobar.io"
    keyId: "Gb389a-9f76-gdjs-a92j-0242bk99999"
```

Sorry for my confusion.
