### ISSUE TITLE
KeyError on Superset dashboard Ingestion

### ISSUE THREAD

**Issue by a-cid** [open-metadata/OpenMetadata#8547]
**Affected module**
Ingestion Framework

**Describe the bug**
A KeyError is thrown [here](https://github.com/open-metadata/OpenMetadata/blob/a7347e1873d3b23251a02d262dcd066158bfa3c5/ingestion/src/metadata/ingestion/source/dashboard/superset.py#L269) when ingesting Superset dashboards for a database configured using AWS Athena, because `database_json["result"]["parameters"]` is an empty dictionary.

I replaced `database_json["result"]["parameters"]["database"]` with `"default"`, as that was the database name used by the metadata ingested from Athena, and that fixed the issue for my particular case.

**To Reproduce**

Ingest Superset dashboards with an Athena datasource.

**Expected behavior**
Set database_name as `"default"` if `database_json["result"]["backend"] == "awsathena"`

**Version:**
 - OS: Ubuntu
 - Python version: 3.10.6
 - OpenMetadata version: 0.12.2
 - OpenMetadata Ingestion package version: [main branch](https://github.com/open-metadata/OpenMetadata/commit/158bd4b9cd5a7fae71dd10d3de1dc7520fa659d3)

**Additional context**

I'm running the ingestion process outside Airflow, with the following script:

```
from metadata.cli.ingest import run_ingest

run_ingest('superset_ingestion.yaml')
```

superset_ingestion.yaml:

```
source:
  type: superset
  serviceName: local_superset
  serviceConnection:
    config:
      type: Superset
      hostPort: <redacted>
      username: <redacted>
      password: <redacted>
  sourceConfig:
    config:
      type: DashboardMetadata
      dbServiceNames:
        - local_athena
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG 
  openMetadataServerConfig:
    hostPort: http://localhost:8585/api
    authProvider: openmetadata
    securityConfig:
      jwtToken: <redacted>
```
