### ISSUE TITLE
Can't run snowflake ingestion. snowflake-sqlalchemy requires upgrade

### ISSUE THREAD

**Issue by stephanesol** [open-metadata/OpenMetadata#8598]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?

ingestion framework

**Describe the bug**

Unable to run snowflake metadata ingestion after installing requirements.

![image](https://user-images.githubusercontent.com/6843613/200694403-1f61f052-efe4-476d-a7bd-a17549f2c0c5.png)

**To Reproduce**

```bash
python3 -m venv env12.2.3
source env12.2.3/bin/activate
pip3 install --upgrade pip setuptools
pip3 install 'openmetadata-ingestion[elasticsearch]'==0.12.2.3
pip3 install "openmetadata-ingestion[snowflake]"==0.12.2.3
pip3 install "openmetadata-ingestion[snowflake-usage]"==0.12.2.3
```

```bash
./env12.2.3/bin/metadata ingest -c snowflake.yaml   
```
snowflake.yaml  
```yaml
source:
  type: snowflake
  serviceName: SNOWFLAKE
  serviceConnection:
    config:
      type: Snowflake
      username: ****
      password: ****
      warehouse: ****
      account: ****
      role: ****

  sourceConfig:
    config:
      type: DatabaseMetadata
      markDeletedTables: false
      markDeletedTablesFromFilterOnly: false
      includeTables: true
      includeViews: true
      includeTags: false
      databaseFilterPattern:
        includes:
          - DWH_PROD
      schemaFilterPattern:
        includes:
          - CANONICAL
      dbtConfigSource:
      # For cloud
        dbtCloudAuthToken: ****
        dbtCloudAccountId: ****
        dbtCloudProjectId: ****
        dbtUpdateDescriptions: true
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: DEBUG
  openMetadataServerConfig:
    hostPort: https://****/api
    enableVersionValidation: False
    authProvider: openmetadata
    securityConfig:
      jwtToken: '****'
```

Screenshots or steps to reproduce

**Expected behavior**

Ingestion should complete without adding/updating packages via pip.

**Version:**
 - OS: `macOS Monterey 12.5.1`
 - Python version: `3.10.8` 
 - OpenMetadata version: `0.12.2.2`
 - OpenMetadata Ingestion package version: `0.12.2.3`

**Additional context**

Here is the related issue in sql-alchemy https://github.com/snowflakedb/snowflake-sqlalchemy/issues/350

Work around is to perform `pip install snowflake-sqlalchemy --upgrade` but this can't be done in certain environments like managed Airflow.

![image](https://user-images.githubusercontent.com/6843613/200695256-b6a6fee4-622f-4eb8-b517-409c8ff3fc33.png)
