### ISSUE TITLE
Cannot use local volumes in docker compose's airflow

### ISSUE THREAD

**Issue by martsec** [open-metadata/OpenMetadata#9442]
**Affected module**
Ingestion Framework

**Describe the bug**
When adding in the docker compose the local volumes, they are created with permissions `1000:1000` instead of `airflow:root` 

This gives errors when adding metadata pipelines like: 

```
XYZ Failed to deploy Ingestion Pipeline due to airflow API returned Internal Server Error and response {"error": "Internal error while deploying due to [[Errno 13] Permission denied: '/opt/airflow/dag_generated_configs/XYZ.json'] "}
```
```
XYZ Failed to deploy Ingestion Pipeline due to airflow API returned Internal Server Error and response {"error": "Internal error while deploying due to [[Errno 13] Permission denied: '/opt/airflow/dags/XYZ.py'] "}
```

**To Reproduce**

1. Download the docker-compose file from https://docs.open-metadata.org/deployment/docker
2. Modify the volumes as specified in here https://docs.open-metadata.org/deployment/docker/volumes

Example:
```yaml
  ingestion:
    container_name: openmetadata_ingestion
    image: openmetadata/ingestion:0.13.0
   ...
    volumes:
      - ./docker-volume/dag_config:/opt/airflow/dag_generated_configs
      - ./docker-volume/dags:/opt/airflow/dags
      - ./docker-volume/secrets:/tmp
```

3. Do `docker compose up`
4. Add a database (I used redshift)
5. Configure a metadata ingestion for that database
6. Pipeline will fail to create with the errors mentioned before

**Expected behavior**

**Version:**
 - OS: Ubuntu, Docker version 20.10.21 
 - Python version: N/A
 - OpenMetadata version: 0.13.0
 - OpenMetadata Ingestion package version: openmetadata/ingestion:0.13.0

**Additional context**

To manually fix it, the following needs to be executed:

```bash
docker exec -u 0 -it openmetadata_ingestion bash
chown airflow:root dag_generated_configs
chown airflow:root dags
chown airflow:root /tmp
```

I suppose the dockerfiles for the ingestion needs to be fixed

* https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/Dockerfile.ci
* https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/Dockerfile

```
RUN chown airflow:root /opt/airflow/dags /opt/airflow/dag_generated_configs /tmp
```
